import type { LanguageCode } from "@/lib/site-language";

export type MyBondCopy = {
  loginSignup: string;
  logout: string;
  authTitle: string;
  authSubtitle: string;
  authImageAlt: string;
  email: string;
  password: string;
  continueWithEmail: string;
  oneMoment: string;
  enterEmailPassword: string;
  loginNotConfigured: string;
  checkEmail: string;
  legalPrefix: string;
  termsOfUse: string;
  and: string;
  privacyPolicy: string;
  close: string;
  loadingBond: string;
  lockedTitle: string;
  lockedDescription: string;
  dashboardEyebrow: string;
  welcomeBack: string;
  messagesLeft: string;
  buyMessages: string;
  recentChats: string;
  createdCompanions: string;
  favorites: string;
  continueChat: string;
  noRecentChats: string;
  startChatting: string;
  myCompanions: string;
  characterLimit: string;
  createCompanion: string;
  all: string;
  public: string;
  private: string;
  noCompanions: string;
  openCompanion: string;
  favoriteCompanions: string;
  noFavorites: string;
  exploreCompanions: string;
  accountInformation: string;
  accountEmail: string;
  username: string;
  memberSince: string;
  purchaseHistory: string;
  noPurchases: string;
  purchasesWillAppear: string;
  loadError: string;
  retry: string;
  editUsername: string;
  saveUsername: string;
  cancel: string;
  usernamePlaceholder: string;
  usernameRequirements: string;
  usernameUpdated: string;
  usernameTaken: string;
  invalidUsername: string;
  usernameUpdateFailed: string;
  savingUsername: string;
  createdBy: string;
  creatorPublicCharacters: string;
  creatorPublicCharactersDescription: string;
  noPublicCharacters: string;
  privateCompanionLoading: string;
  privateCompanionLoginRequired: string;
  privateCompanionUnavailable: string;
  editCompanion: string;
  deleteCompanion: string;
  editCompanionTitle: string;
  saveCompanion: string;
  savingCompanion: string;
  companionUpdated: string;
  companionUpdateFailed: string;
  deleteCompanionTitle: string;
  deleteCompanionConfirmation: string;
  deletingCompanion: string;
  companionDeleted: string;
  companionDeleteFailed: string;
  optionalReplacementImage: string;
};

export const MY_BOND_COPY: Record<LanguageCode, MyBondCopy> = {
  EN: {
    loginSignup: "Log in / Sign up",
    logout: "Log out",
    authTitle: "Start your bond",
    authSubtitle: "Your bonds, stories, and memories—all in one place.",
    authImageAlt: "Welcome to Uncensored Girlfriend",
    email: "Email",
    password: "Password",
    continueWithEmail: "Continue with email",
    oneMoment: "One moment...",
    enterEmailPassword: "Enter your email and password.",
    loginNotConfigured: "Login is not configured yet.",
    checkEmail: "Check your email to finish creating your account.",
    legalPrefix: "By continuing, you confirm that you are of legal age and agree to our",
    termsOfUse: "Terms of Use",
    and: "and",
    privacyPolicy: "Privacy Policy",
    close: "Close",
    loadingBond: "Loading your bond...",
    lockedTitle: "Log in or sign up to access My Companions.",
    lockedDescription:
      "My Companions is where your favorites, chats, account details, created companions, and personal Uncensored Girlfriend info will live.",
    dashboardEyebrow: "MY BOND",
    welcomeBack: "Welcome back",
    messagesLeft: "Messages Left",
    buyMessages: "Buy Messages",
    recentChats: "Recent Chats",
    createdCompanions: "Created Companions",
    favorites: "Favorites",
    continueChat: "Continue Chat",
    noRecentChats: "No recent chats yet.",
    startChatting: "Explore Companions",
    myCompanions: "My Companions",
    characterLimit: "of 100 created",
    createCompanion: "Create Companion",
    all: "All",
    public: "Public",
    private: "Private",
    noCompanions: "You have not created any companions in this section yet.",
    openCompanion: "Open Companion",
    favoriteCompanions: "Favorite Companions",
    noFavorites: "You have not saved any favorites yet.",
    exploreCompanions: "Explore Companions",
    accountInformation: "Account Information",
    accountEmail: "Email",
    username: "Username",
    memberSince: "Member Since",
    purchaseHistory: "Purchase History",
    noPurchases: "No purchases yet.",
    purchasesWillAppear:
      "Message-bundle and KissCoins purchases will appear here after Paddle is connected.",
    loadError: "My Companions could not be loaded.",
    retry: "Try Again",
    editUsername: "Edit",
    saveUsername: "Save",
    cancel: "Cancel",
    usernamePlaceholder: "username",
    usernameRequirements: "Use 3–30 lowercase letters, numbers, or underscores.",
    usernameUpdated: "Username updated.",
    usernameTaken: "That username is already taken.",
    invalidUsername: "Enter a valid username using 3–30 lowercase letters, numbers, or underscores.",
    usernameUpdateFailed: "The username could not be updated.",
    savingUsername: "Saving...",
    createdBy: "Created by",
    creatorPublicCharacters: "Public Companions",
    creatorPublicCharactersDescription: "Explore this creator’s public companions and start a chat.",
    noPublicCharacters: "This creator does not have any public companions yet.",
    privateCompanionLoading: "Loading your private companion...",
    privateCompanionLoginRequired: "Log in to open this private companion.",
    privateCompanionUnavailable: "This private companion is only available to its creator.",
    editCompanion: "Edit",
    deleteCompanion: "Delete",
    editCompanionTitle: "Edit Companion",
    saveCompanion: "Save Changes",
    savingCompanion: "Saving...",
    companionUpdated: "Companion updated.",
    companionUpdateFailed: "The companion could not be updated.",
    deleteCompanionTitle: "Delete Companion",
    deleteCompanionConfirmation: "Delete this companion permanently? Its chats and saved memory will also be removed.",
    deletingCompanion: "Deleting...",
    companionDeleted: "Companion deleted.",
    companionDeleteFailed: "The companion could not be deleted.",
    optionalReplacementImage: "Optional replacement image"
  },
  ES: {
    loginSignup: "Iniciar sesión / Registrarse",
    logout: "Cerrar sesión",
    authTitle: "Comienza tu vínculo",
    authSubtitle: "Tus vínculos, historias y recuerdos, todos en un solo lugar.",
    authImageAlt: "Bienvenido a Uncensored Girlfriend",
    email: "Correo electrónico",
    password: "Contraseña",
    continueWithEmail: "Continuar con correo",
    oneMoment: "Un momento...",
    enterEmailPassword: "Introduce tu correo electrónico y contraseña.",
    loginNotConfigured: "El inicio de sesión aún no está configurado.",
    checkEmail: "Revisa tu correo para terminar de crear tu cuenta.",
    legalPrefix: "Al continuar, confirmas que tienes la edad legal y aceptas nuestros",
    termsOfUse: "Términos de uso",
    and: "y",
    privacyPolicy: "Política de privacidad",
    close: "Cerrar",
    loadingBond: "Cargando tu vínculo...",
    lockedTitle: "Inicia sesión o regístrate para acceder a Mi Vínculo.",
    lockedDescription:
      "Mi Vínculo es donde estarán tus favoritos, chats, detalles de cuenta, compañeros creados e información personal de Uncensored Girlfriend.",
    dashboardEyebrow: "MI VÍNCULO",
    welcomeBack: "Te damos la bienvenida",
    messagesLeft: "Mensajes restantes",
    buyMessages: "Comprar mensajes",
    recentChats: "Chats recientes",
    createdCompanions: "Compañeros creados",
    favorites: "Favoritos",
    continueChat: "Continuar chat",
    noRecentChats: "Aún no tienes chats recientes.",
    startChatting: "Explorar compañeros",
    myCompanions: "Mis compañeros",
    characterLimit: "de 100 creados",
    createCompanion: "Crear compañero",
    all: "Todos",
    public: "Públicos",
    private: "Privados",
    noCompanions: "Todavía no has creado compañeros en esta sección.",
    openCompanion: "Abrir compañero",
    favoriteCompanions: "Compañeros favoritos",
    noFavorites: "Todavía no has guardado favoritos.",
    exploreCompanions: "Explorar compañeros",
    accountInformation: "Información de la cuenta",
    accountEmail: "Correo electrónico",
    username: "Nombre de usuario",
    memberSince: "Miembro desde",
    purchaseHistory: "Historial de compras",
    noPurchases: "Aún no hay compras.",
    purchasesWillAppear:
      "Las compras de paquetes de mensajes y KissCoins aparecerán aquí cuando Paddle esté conectado.",
    loadError: "No se pudo cargar Mi Vínculo.",
    retry: "Intentar de nuevo",
    editUsername: "Editar",
    saveUsername: "Guardar",
    cancel: "Cancelar",
    usernamePlaceholder: "nombre_de_usuario",
    usernameRequirements: "Usa entre 3 y 30 letras minúsculas, números o guiones bajos.",
    usernameUpdated: "Nombre de usuario actualizado.",
    usernameTaken: "Ese nombre de usuario ya está en uso.",
    invalidUsername: "Introduce un nombre válido de 3 a 30 letras minúsculas, números o guiones bajos.",
    usernameUpdateFailed: "No se pudo actualizar el nombre de usuario.",
    savingUsername: "Guardando...",
    createdBy: "Creado por",
    creatorPublicCharacters: "Compañeros públicos",
    creatorPublicCharactersDescription: "Explora los compañeros públicos de este creador y comienza un chat.",
    noPublicCharacters: "Este creador todavía no tiene compañeros públicos.",
    privateCompanionLoading: "Cargando tu compañero privado...",
    privateCompanionLoginRequired: "Inicia sesión para abrir este compañero privado.",
    privateCompanionUnavailable: "Este compañero privado solo está disponible para su creador.",
    editCompanion: "Editar",
    deleteCompanion: "Eliminar",
    editCompanionTitle: "Editar compañero",
    saveCompanion: "Guardar cambios",
    savingCompanion: "Guardando...",
    companionUpdated: "Compañero actualizado.",
    companionUpdateFailed: "No se pudo actualizar el compañero.",
    deleteCompanionTitle: "Eliminar compañero",
    deleteCompanionConfirmation: "¿Eliminar este compañero permanentemente? También se eliminarán sus chats y memoria guardada.",
    deletingCompanion: "Eliminando...",
    companionDeleted: "Compañero eliminado.",
    companionDeleteFailed: "No se pudo eliminar el compañero.",
    optionalReplacementImage: "Imagen de reemplazo opcional"
  },
  FR: {
    loginSignup: "Connexion / Inscription",
    logout: "Se déconnecter",
    authTitle: "Commencez votre lien",
    authSubtitle: "Vos liens, vos histoires et vos souvenirs, réunis au même endroit.",
    authImageAlt: "Bienvenue sur Uncensored Girlfriend",
    email: "E-mail",
    password: "Mot de passe",
    continueWithEmail: "Continuer avec l’e-mail",
    oneMoment: "Un instant...",
    enterEmailPassword: "Saisissez votre e-mail et votre mot de passe.",
    loginNotConfigured: "La connexion n’est pas encore configurée.",
    checkEmail: "Consultez votre e-mail pour terminer la création de votre compte.",
    legalPrefix: "En continuant, vous confirmez avoir l’âge légal et accepter nos",
    termsOfUse: "Conditions d’utilisation",
    and: "et notre",
    privacyPolicy: "Politique de confidentialité",
    close: "Fermer",
    loadingBond: "Chargement de votre lien...",
    lockedTitle: "Connectez-vous ou inscrivez-vous pour accéder à Mon Lien.",
    lockedDescription:
      "Mon Lien rassemble vos favoris, vos chats, les informations de votre compte, vos compagnons créés et vos données personnelles Uncensored Girlfriend.",
    dashboardEyebrow: "MON LIEN",
    welcomeBack: "Heureux de vous revoir",
    messagesLeft: "Messages restants",
    buyMessages: "Acheter des messages",
    recentChats: "Chats récents",
    createdCompanions: "Compagnons créés",
    favorites: "Favoris",
    continueChat: "Continuer le chat",
    noRecentChats: "Aucun chat récent pour le moment.",
    startChatting: "Explorer les compagnons",
    myCompanions: "Mes compagnons",
    characterLimit: "sur 100 créés",
    createCompanion: "Créer un compagnon",
    all: "Tous",
    public: "Publics",
    private: "Privés",
    noCompanions: "Vous n’avez encore créé aucun compagnon dans cette section.",
    openCompanion: "Ouvrir le compagnon",
    favoriteCompanions: "Compagnons favoris",
    noFavorites: "Vous n’avez encore enregistré aucun favori.",
    exploreCompanions: "Explorer les compagnons",
    accountInformation: "Informations du compte",
    accountEmail: "E-mail",
    username: "Nom d’utilisateur",
    memberSince: "Membre depuis",
    purchaseHistory: "Historique des achats",
    noPurchases: "Aucun achat pour le moment.",
    purchasesWillAppear:
      "Les achats de packs de messages et d’KissCoins apparaîtront ici une fois Paddle connecté.",
    loadError: "Impossible de charger Mon Lien.",
    retry: "Réessayer",
    editUsername: "Modifier",
    saveUsername: "Enregistrer",
    cancel: "Annuler",
    usernamePlaceholder: "nom_utilisateur",
    usernameRequirements: "Utilisez 3 à 30 lettres minuscules, chiffres ou traits de soulignement.",
    usernameUpdated: "Nom d’utilisateur mis à jour.",
    usernameTaken: "Ce nom d’utilisateur est déjà utilisé.",
    invalidUsername: "Saisissez un nom valide de 3 à 30 lettres minuscules, chiffres ou traits de soulignement.",
    usernameUpdateFailed: "Le nom d’utilisateur n’a pas pu être mis à jour.",
    savingUsername: "Enregistrement...",
    createdBy: "Créé par",
    creatorPublicCharacters: "Compagnons publics",
    creatorPublicCharactersDescription: "Découvrez les compagnons publics de ce créateur et commencez un chat.",
    noPublicCharacters: "Ce créateur ne possède encore aucun compagnon public.",
    privateCompanionLoading: "Chargement de votre compagnon privé...",
    privateCompanionLoginRequired: "Connectez-vous pour ouvrir ce compagnon privé.",
    privateCompanionUnavailable: "Ce compagnon privé est uniquement accessible à son créateur.",
    editCompanion: "Modifier",
    deleteCompanion: "Supprimer",
    editCompanionTitle: "Modifier le compagnon",
    saveCompanion: "Enregistrer",
    savingCompanion: "Enregistrement...",
    companionUpdated: "Compagnon mis à jour.",
    companionUpdateFailed: "Impossible de mettre à jour le compagnon.",
    deleteCompanionTitle: "Supprimer le compagnon",
    deleteCompanionConfirmation: "Supprimer définitivement ce compagnon ? Ses chats et sa mémoire enregistrée seront également supprimés.",
    deletingCompanion: "Suppression...",
    companionDeleted: "Compagnon supprimé.",
    companionDeleteFailed: "Impossible de supprimer le compagnon.",
    optionalReplacementImage: "Image de remplacement facultative"
  },
  JA: {
    loginSignup: "ログイン / 新規登録",
    logout: "ログアウト",
    authTitle: "絆を始める",
    authSubtitle: "あなたの絆、物語、記憶をひとつの場所に。",
    authImageAlt: "Uncensored Girlfriend へようこそ",
    email: "メールアドレス",
    password: "パスワード",
    continueWithEmail: "メールで続ける",
    oneMoment: "少々お待ちください...",
    enterEmailPassword: "メールアドレスとパスワードを入力してください。",
    loginNotConfigured: "ログインはまだ設定されていません。",
    checkEmail: "アカウント作成を完了するため、メールを確認してください。",
    legalPrefix: "続行すると、法定年齢に達しており、以下に同意したものとみなされます。",
    termsOfUse: "利用規約",
    and: "および",
    privacyPolicy: "プライバシーポリシー",
    close: "閉じる",
    loadingBond: "あなたの絆を読み込んでいます...",
    lockedTitle: "My Companions を利用するには、ログインまたは新規登録してください。",
    lockedDescription:
      "My Companions には、お気に入り、チャット、アカウント情報、作成したコンパニオン、個人の Uncensored Girlfriend 情報が保存されます。",
    dashboardEyebrow: "MY BOND",
    welcomeBack: "おかえりなさい",
    messagesLeft: "残りメッセージ",
    buyMessages: "メッセージを購入",
    recentChats: "最近のチャット",
    createdCompanions: "作成したコンパニオン",
    favorites: "お気に入り",
    continueChat: "チャットを続ける",
    noRecentChats: "最近のチャットはまだありません。",
    startChatting: "コンパニオンを探す",
    myCompanions: "マイコンパニオン",
    characterLimit: "作成済み / 100",
    createCompanion: "コンパニオンを作成",
    all: "すべて",
    public: "公開",
    private: "非公開",
    noCompanions: "このセクションには、まだコンパニオンがありません。",
    openCompanion: "コンパニオンを開く",
    favoriteCompanions: "お気に入りのコンパニオン",
    noFavorites: "お気に入りはまだ保存されていません。",
    exploreCompanions: "コンパニオンを探す",
    accountInformation: "アカウント情報",
    accountEmail: "メールアドレス",
    username: "ユーザー名",
    memberSince: "登録日",
    purchaseHistory: "購入履歴",
    noPurchases: "購入履歴はまだありません。",
    purchasesWillAppear:
      "Paddle 接続後、メッセージバンドルと KissCoins の購入がここに表示されます。",
    loadError: "My Companions を読み込めませんでした。",
    retry: "再試行",
    editUsername: "編集",
    saveUsername: "保存",
    cancel: "キャンセル",
    usernamePlaceholder: "ユーザー名",
    usernameRequirements: "3〜30文字の小文字、数字、またはアンダースコアを使用してください。",
    usernameUpdated: "ユーザー名を更新しました。",
    usernameTaken: "そのユーザー名はすでに使用されています。",
    invalidUsername: "3〜30文字の小文字、数字、またはアンダースコアで有効なユーザー名を入力してください。",
    usernameUpdateFailed: "ユーザー名を更新できませんでした。",
    savingUsername: "保存中...",
    createdBy: "作成者",
    creatorPublicCharacters: "公開コンパニオン",
    creatorPublicCharactersDescription: "このクリエイターの公開コンパニオンを見て、チャットを始めましょう。",
    noPublicCharacters: "このクリエイターには、まだ公開コンパニオンがありません。",
    privateCompanionLoading: "非公開コンパニオンを読み込んでいます...",
    privateCompanionLoginRequired: "この非公開コンパニオンを開くにはログインしてください。",
    privateCompanionUnavailable: "この非公開コンパニオンは作成者のみ利用できます。",
    editCompanion: "編集",
    deleteCompanion: "削除",
    editCompanionTitle: "コンパニオンを編集",
    saveCompanion: "変更を保存",
    savingCompanion: "保存中...",
    companionUpdated: "コンパニオンを更新しました。",
    companionUpdateFailed: "コンパニオンを更新できませんでした。",
    deleteCompanionTitle: "コンパニオンを削除",
    deleteCompanionConfirmation: "このコンパニオンを完全に削除しますか？チャットと保存されたメモリーも削除されます。",
    deletingCompanion: "削除中...",
    companionDeleted: "コンパニオンを削除しました。",
    companionDeleteFailed: "コンパニオンを削除できませんでした。",
    optionalReplacementImage: "任意の差し替え画像"
  },
  DE: {
    loginSignup: "Anmelden / Registrieren",
    logout: "Abmelden",
    authTitle: "Beginne deine Bindung",
    authSubtitle: "Deine Bindungen, Geschichten und Erinnerungen an einem Ort.",
    authImageAlt: "Willkommen bei Uncensored Girlfriend",
    email: "E-Mail",
    password: "Passwort",
    continueWithEmail: "Mit E-Mail fortfahren",
    oneMoment: "Einen Moment...",
    enterEmailPassword: "Gib deine E-Mail-Adresse und dein Passwort ein.",
    loginNotConfigured: "Die Anmeldung ist noch nicht eingerichtet.",
    checkEmail: "Prüfe deine E-Mail, um die Kontoerstellung abzuschließen.",
    legalPrefix: "Wenn du fortfährst, bestätigst du dein gesetzliches Mindestalter und stimmst unseren",
    termsOfUse: "Nutzungsbedingungen",
    and: "und unserer",
    privacyPolicy: "Datenschutzerklärung",
    close: "Schließen",
    loadingBond: "Deine Bindung wird geladen...",
    lockedTitle: "Melde dich an oder registriere dich, um auf Meine Bindung zuzugreifen.",
    lockedDescription:
      "Meine Bindung ist der Ort für deine Favoriten, Chats, Kontodaten, erstellten Begleiter und persönlichen Uncensored Girlfriend-Informationen.",
    dashboardEyebrow: "MEINE BINDUNG",
    welcomeBack: "Willkommen zurück",
    messagesLeft: "Verbleibende Nachrichten",
    buyMessages: "Nachrichten kaufen",
    recentChats: "Letzte Chats",
    createdCompanions: "Erstellte Begleiter",
    favorites: "Favoriten",
    continueChat: "Chat fortsetzen",
    noRecentChats: "Noch keine letzten Chats.",
    startChatting: "Begleiter entdecken",
    myCompanions: "Meine Begleiter",
    characterLimit: "von 100 erstellt",
    createCompanion: "Begleiter erstellen",
    all: "Alle",
    public: "Öffentlich",
    private: "Privat",
    noCompanions: "Du hast in diesem Bereich noch keine Begleiter erstellt.",
    openCompanion: "Begleiter öffnen",
    favoriteCompanions: "Favorisierte Begleiter",
    noFavorites: "Du hast noch keine Favoriten gespeichert.",
    exploreCompanions: "Begleiter entdecken",
    accountInformation: "Kontoinformationen",
    accountEmail: "E-Mail",
    username: "Benutzername",
    memberSince: "Mitglied seit",
    purchaseHistory: "Kaufverlauf",
    noPurchases: "Noch keine Käufe.",
    purchasesWillAppear:
      "Nachrichtenpaket- und KissCoins-Käufe erscheinen hier, sobald Paddle verbunden ist.",
    loadError: "Meine Bindung konnte nicht geladen werden.",
    retry: "Erneut versuchen",
    editUsername: "Bearbeiten",
    saveUsername: "Speichern",
    cancel: "Abbrechen",
    usernamePlaceholder: "benutzername",
    usernameRequirements: "Verwende 3–30 Kleinbuchstaben, Zahlen oder Unterstriche.",
    usernameUpdated: "Benutzername aktualisiert.",
    usernameTaken: "Dieser Benutzername ist bereits vergeben.",
    invalidUsername: "Gib einen gültigen Benutzernamen mit 3–30 Kleinbuchstaben, Zahlen oder Unterstrichen ein.",
    usernameUpdateFailed: "Der Benutzername konnte nicht aktualisiert werden.",
    savingUsername: "Wird gespeichert...",
    createdBy: "Erstellt von",
    creatorPublicCharacters: "Öffentliche Begleiter",
    creatorPublicCharactersDescription: "Entdecke die öffentlichen Begleiter dieses Erstellers und beginne einen Chat.",
    noPublicCharacters: "Dieser Ersteller hat noch keine öffentlichen Begleiter.",
    privateCompanionLoading: "Dein privater Begleiter wird geladen...",
    privateCompanionLoginRequired: "Melde dich an, um diesen privaten Begleiter zu öffnen.",
    privateCompanionUnavailable: "Dieser private Begleiter ist nur für seinen Ersteller verfügbar.",
    editCompanion: "Bearbeiten",
    deleteCompanion: "Löschen",
    editCompanionTitle: "Begleiter bearbeiten",
    saveCompanion: "Änderungen speichern",
    savingCompanion: "Speichern...",
    companionUpdated: "Begleiter aktualisiert.",
    companionUpdateFailed: "Der Begleiter konnte nicht aktualisiert werden.",
    deleteCompanionTitle: "Begleiter löschen",
    deleteCompanionConfirmation: "Diesen Begleiter dauerhaft löschen? Seine Chats und gespeicherte Erinnerung werden ebenfalls entfernt.",
    deletingCompanion: "Löschen...",
    companionDeleted: "Begleiter gelöscht.",
    companionDeleteFailed: "Der Begleiter konnte nicht gelöscht werden.",
    optionalReplacementImage: "Optionales Ersatzbild"
  },
  KO: {
    loginSignup: "로그인 / 회원가입",
    logout: "로그아웃",
    authTitle: "유대를 시작하세요",
    authSubtitle: "당신의 유대, 이야기, 기억을 한곳에서 만나보세요.",
    authImageAlt: "Uncensored Girlfriend에 오신 것을 환영합니다",
    email: "이메일",
    password: "비밀번호",
    continueWithEmail: "이메일로 계속",
    oneMoment: "잠시만요...",
    enterEmailPassword: "이메일과 비밀번호를 입력하세요.",
    loginNotConfigured: "로그인이 아직 설정되지 않았습니다.",
    checkEmail: "계정 생성을 완료하려면 이메일을 확인하세요.",
    legalPrefix: "계속하면 법적 연령에 도달했으며 다음에 동의함을 확인합니다.",
    termsOfUse: "이용 약관",
    and: "및",
    privacyPolicy: "개인정보 처리방침",
    close: "닫기",
    loadingBond: "유대를 불러오는 중...",
    lockedTitle: "My Companions를 이용하려면 로그인하거나 회원가입하세요.",
    lockedDescription:
      "My Companions에는 즐겨찾기, 채팅, 계정 정보, 만든 컴패니언, 개인 Uncensored Girlfriend 정보가 저장됩니다.",
    dashboardEyebrow: "MY BOND",
    welcomeBack: "다시 오신 것을 환영합니다",
    messagesLeft: "남은 메시지",
    buyMessages: "메시지 구매",
    recentChats: "최근 채팅",
    createdCompanions: "만든 컴패니언",
    favorites: "즐겨찾기",
    continueChat: "채팅 계속",
    noRecentChats: "아직 최근 채팅이 없습니다.",
    startChatting: "컴패니언 둘러보기",
    myCompanions: "내 컴패니언",
    characterLimit: "100개 중 생성",
    createCompanion: "컴패니언 만들기",
    all: "전체",
    public: "공개",
    private: "비공개",
    noCompanions: "이 섹션에는 아직 만든 컴패니언이 없습니다.",
    openCompanion: "컴패니언 열기",
    favoriteCompanions: "즐겨찾는 컴패니언",
    noFavorites: "아직 저장한 즐겨찾기가 없습니다.",
    exploreCompanions: "컴패니언 둘러보기",
    accountInformation: "계정 정보",
    accountEmail: "이메일",
    username: "사용자 이름",
    memberSince: "가입일",
    purchaseHistory: "구매 내역",
    noPurchases: "아직 구매 내역이 없습니다.",
    purchasesWillAppear:
      "Paddle 연결 후 메시지 번들과 KissCoins 구매 내역이 여기에 표시됩니다.",
    loadError: "My Companions를 불러올 수 없습니다.",
    retry: "다시 시도",
    editUsername: "수정",
    saveUsername: "저장",
    cancel: "취소",
    usernamePlaceholder: "사용자_이름",
    usernameRequirements: "영문 소문자, 숫자 또는 밑줄을 사용해 3~30자로 입력하세요.",
    usernameUpdated: "사용자 이름이 업데이트되었습니다.",
    usernameTaken: "이미 사용 중인 사용자 이름입니다.",
    invalidUsername: "영문 소문자, 숫자 또는 밑줄을 사용해 3~30자의 유효한 사용자 이름을 입력하세요.",
    usernameUpdateFailed: "사용자 이름을 업데이트할 수 없습니다.",
    savingUsername: "저장 중...",
    createdBy: "제작자",
    creatorPublicCharacters: "공개 컴패니언",
    creatorPublicCharactersDescription: "이 제작자의 공개 컴패니언을 둘러보고 채팅을 시작하세요.",
    noPublicCharacters: "이 제작자에게는 아직 공개 컴패니언이 없습니다.",
    privateCompanionLoading: "비공개 컴패니언을 불러오는 중...",
    privateCompanionLoginRequired: "이 비공개 컴패니언을 열려면 로그인하세요.",
    privateCompanionUnavailable: "이 비공개 컴패니언은 제작자만 이용할 수 있습니다.",
    editCompanion: "편집",
    deleteCompanion: "삭제",
    editCompanionTitle: "컴패니언 편집",
    saveCompanion: "변경 사항 저장",
    savingCompanion: "저장 중...",
    companionUpdated: "컴패니언이 업데이트되었습니다.",
    companionUpdateFailed: "컴패니언을 업데이트하지 못했습니다.",
    deleteCompanionTitle: "컴패니언 삭제",
    deleteCompanionConfirmation: "이 컴패니언을 영구 삭제할까요? 채팅과 저장된 메모리도 함께 삭제됩니다.",
    deletingCompanion: "삭제 중...",
    companionDeleted: "컴패니언이 삭제되었습니다.",
    companionDeleteFailed: "컴패니언을 삭제하지 못했습니다.",
    optionalReplacementImage: "선택 사항인 교체 이미지"
  }
};
