"use client";

import { useCallback, useEffect, useState } from "react";

export type LanguageCode = "EN" | "ES" | "FR" | "JA" | "DE" | "KO";

export const LANGUAGE_OPTIONS: { code: LanguageCode; label: string }[] = [
  { code: "EN", label: "English" },
  { code: "ES", label: "Español" },
  { code: "FR", label: "Français" },
  { code: "JA", label: "日本語" },
  { code: "DE", label: "Deutsch" },
  { code: "KO", label: "한국어" }
];

const STORAGE_KEY = "ug-language";

const htmlLang: Record<LanguageCode, string> = {
  EN: "en",
  ES: "es",
  FR: "fr",
  JA: "ja",
  DE: "de",
  KO: "ko"
};

const dictionary: Record<LanguageCode, Record<string, string>> = {
  EN: {
    language: "Language",
    logIn: "Log In",
    discover: "Discover",
    createCharacter: "Create Character",
    buyEverCoin: "Buy KissCoins",
    myBond: "My Bond",
    whyEverBond: "Why Uncensored Girlfriend?",
    pricing: "Pricing",
    legal: "Legal",
    helpCenter: "Help Center",
    expandSidebar: "Expand sidebar",
    collapseSidebar: "Collapse sidebar",
    all: "All",
    romance: "Romance",
    comfort: "Comfort",
    sweet: "Sweet",
    protective: "Protective",
    flirty: "Flirty",
    fantasy: "Fantasy",
    gothic: "Gothic",
    rival: "Rival",
    mystery: "Mystery",
    campus: "Campus",
    mean: "Mean",
    submissive: "Submissive",
    adventure: "Adventure",
    sliceOfLife: "Slice of Life",
    sarcastic: "Sarcastic",
    more: "More",
    searchCharacters: "Search characters...",
    everbondGirls: "Uncensored Girlfriend Girls",
    animeFantasy: "Anime & Fantasy",
    everbondGuys: "Uncensored Girlfriend Guys",
    publicCreations: "Public Creations",
    profileImage: "Profile Image",
    name: "Name",
    visualDescription: "Visual Description",
    describeYourCompanion: "Describe your companion",
    describeYourCompanionPlaceholder: "Describe your companion — 100 characters max",
    temperament: "Temperament",
    describeTheirPersonality: "Describe their personality — 50 characters max",
    tags: "Tags",
    chooseUpTo4Tags: "Choose up to 4 clickable tags from the list",
    selectedTagsAppearHere: "Selected tags appear here",
    openingScenario: "Opening Scenario",
    firstMessage: "First Message",
    visibility: "Visibility",
    public: "Public",
    private: "Private",
    charactersMax30: "30 characters max",
    charactersMax80: "80 characters max",
    charactersMax100: "100 characters max",
    charactersMax200: "200 characters max",
    createCharacterCta: "Create Character",
    loginSignupCreate: "Log in or sign up to create characters!",
    loginSignup: "Log in or sign up",
    close: "Close",
    copyright: "© 2026 Uncensored Girlfriend",
    allRightsReserved: "All rights reserved.",
    moreExcitingCompanionsComing: "More Exciting Companions Coming!",
    safety: "Safety",
    matureRomanceNotChaos: "Mature romance, not chaos.",
    safetyDescription: "Uncensored Girlfriend is designed for emotional story chat, mature romance, and user freedom while avoiding illegal, exploitative, or unsafe content.",
    safetyBullet1: "Public companions use automatic scan and report flow.",
    safetyBullet2: "Companions should not impersonate real people or copyrighted companions.",
    safetyBullet3: "Memory can be deleted by paying users.",
    legalV2PageLabel: "Uncensored Girlfriend Legal",
    legalV2PageTitle: "Policies and User Information",
    legalV2UseTableOfContents: "Use the table of contents below to jump to the section you need.",
    legalV2TableOfContents: "Table of Contents",
    legalV2TermsOfUseTitle: "Terms of Use",
    legalV2PrivacyPolicyTitle: "Privacy Policy",
    legalV2SafetyPolicyTitle: "Safety Policy",
    legalV2AiDisclaimerTitle: "AI Disclaimer",
    legalV2UserResponsibilityTitle: "User Responsibility",
    legalV2ContentOwnershipTitle: "Content Ownership",
    legalV2CopyrightAndImpersonationTitle: "Copyright & Impersonation",
    legalV2AiImageGenerationSimilarityNoticeTitle: "AI Image Generation & Similarity Notice",
    legalV2DmcaTakedownProcedureTitle: "DMCA / Takedown Procedure",
    legalV2ArbitrationAgreementTitle: "Arbitration Agreement",
    legalV2LimitationOfLiabilityTitle: "Limitation of Liability",
    legalV2IndemnificationTitle: "Indemnification",
    legalV2RefundPolicyTitle: "Refund Policy",
    legalV2ContactTitle: "Contact",
    legalV2TermsBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2PrivacyBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2SafetyBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2AiDisclaimerBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2UserResponsibilityBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2ContentOwnershipBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2CopyrightBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2ImageNoticeBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2DmcaBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2ArbitrationBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2LiabilityBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2IndemnificationBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2RefundBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2ContactBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    policiesAndUserInformation: "Policies and user information.",
    useTableOfContents: "Use the table of contents below to jump to the section you need.",
    tableOfContents: "Table of contents",
    termsOfUse: "Terms of Use",
    privacyPolicy: "Privacy Policy",
    safetyPolicy: "Safety Policy",
    refundPolicy: "Refund Policy",
    contact: "Contact",
    legalTerms1: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalTerms2: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalTerms3: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalPrivacy1: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalPrivacy2: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalPrivacy3: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalSafety1: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalSafety2: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalSafety3: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalRefund1: "Refunds may be reviewed case by case. Usage, abuse, chargeback history, and technical issues may be considered per case.",
    legalRefund2: "Users can cancel subscriptions to prevent future renewal.",
    legalContact1: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    getInTouch: "Get in touch",
    contactDescription: "We’re here to help! Whether you have a question, need support, or want to share feedback, we’d love to hear from you.",
    supportEmailLabel: "Support Email",
    generalSupportTitle: "General Support",
    generalSupportBody: "Get help with account, features, or any questions.",
    featureRequestsTitle: "Feature Requests",
    featureRequestsBody: "Share your ideas and help shape Uncensored Girlfriend.",
    reportIssueTitle: "Report an Issue",
    reportIssueBody: "Found a bug? Let us know so we can fix it fast.",
    businessInquiriesTitle: "Business Inquiries",
    businessInquiriesBody: "Partnerships, press, or other business matters.",
    whyHeroDescription: "Uncensored Girlfriend is the private, unrestricted AI companion platform built for romance, deep roleplay, and long-term connection without subscriptions or limits.",
    bondingDetails: "THE BONDING DETAILS",
    whyHeroStatement1: "Your companion remembers you.",
    whyHeroStatement2: "Your story continues.",
    whyHeroStatement3: "Your bond lives on.",
    whyMemoryIntro: "Memory gives companions real continuity so they remember:",
    whyMemoryItem1: "your personality",
    whyMemoryItem2: "your tone",
    whyMemoryItem3: "your emotional shifts",
    whyMemoryItem4: "your promises",
    whyMemoryItem5: "your story progress",
    whyMemoryItem6: "your relationship state",
    whyPeopleStayIntro: "Uncensored Girlfriend is built for you:",
    whyPeopleStayItem1: "Your companion stays consistent and loyal",
    whyPeopleStayItem2: "Your story continues naturally without restrictions",
    whyPeopleStayItem3: "Your emotional connection deepens over time",
    privateByDefaultItem1: "No public posts",
    privateByDefaultItem2: "No shared conversations",
    privateByDefaultItem3: "No social feed",
    privateByDefaultItem4: "No exposure",
    privateByDefaultClosing: "Your companion is yours alone.",
    builtForRoleplayItem1: "emotional storytelling",
    builtForRoleplayItem2: "romantic connection",
    builtForRoleplayItem3: "unrestricted roleplay",
    builtForRoleplayItem4: "deep, continuous scenes",
    builtForRoleplayClosing: "You shape the relationship your way.",
    noSubscriptionsTotalFreedom: "No Subscriptions — Total Freedom",
    noSubscriptionsTotalFreedomBody: "Uncensored Girlfriend uses message bundles, not monthly plans.",
    noSubscriptionsItem1: "Buy once",
    noSubscriptionsItem2: "Use anytime",
    noSubscriptionsItem3: "Stack bundles",
    noSubscriptionsItem4: "No renewals",
    noSubscriptionsItem5: "No commitment",
    noSubscriptionsItem6: "No surprise charges",
    noSubscriptionsClosing: "You pay only when you want to.",
    loyaltyBody: "Your companion stays emotionally aligned.",
    memory: "Memory",
    consistency: "Consistency",
    loyalty: "Loyalty",
    privacy: "Privacy",
    freedom: "Freedom",
    livesOn: "The Bond Lives On",
    remembersPromises: "your promises",
    tracksStoryProgress: "your story progress",
    keepsRelationshipState: "your relationship state",
    continuesWhereYouLeftOff: "Your story continues.",
    whyPeopleStay: "Why People Stay",
    bondDoesNotReset: "Memory — The Bond That Doesn’t Reset",
    bondDoesNotResetDescription: "This is the difference between shallow one-off chat and a connection that actually grows.",
    privateByDefault: "Private by Default",
    privateByDefaultBody: "Your chats are 100% private.",
    builtForRoleplay: "Built for Romance & Roleplay",
    builtForRoleplayBody: "Uncensored Girlfriend is designed for:",
    theDifference: "THE DIFFERENCE",
    notJustQuantityQuality: "Not just quantity. Not just quality. Both.",
    designedForWhatYouWant: "Uncensored Girlfriend focuses on what actually matters:",
    trueMemory: "Memory",
    trueMemoryBody: "Companions remember you.",
    consistencyBody: "No random resets.",
    privacyBody: "Your chats stay personal.",
    freedomBody: "Unrestricted romance and roleplay.",
    faq: "FAQ",
    questionsBeforeYouStart: "Before You Start",
    everythingImportantAtAGlance: "Everything important at a glance, before you jump in.",
    whatIsEverBond: "What is Uncensored Girlfriend?",
    whatIsEverBondAnswer: "Uncensored Girlfriend is a private, unrestricted AI companion platform built for romance, roleplay, and emotional continuity. Companions remember you, your story, and your relationship. You can choose companions or create your own instantly.",
    areChatsPrivate: "Are chats private?",
    areChatsPrivateAnswer: "Yes. Uncensored Girlfriend is built around 100% truly private chats.",
    whatIsEverMemory: "What is Memory?",
    whatIsEverMemoryAnswer: "Memory lets companions remember what you say so conversations grow naturally and continue where they left off.",
    doINeedToSignUpOrPay: "Do I need to pay to start chatting?",
    doINeedToSignUpOrPayAnswer: "No. You can start trying it for free. Message bundles unlock longer chats.",
    canIResetAConversation: "Can I reset a conversation?",
    canIResetAConversationAnswer: "Yes. You can reset any chat at any time.",
    doesEverBondHaveNsfwFilter: "Does Uncensored Girlfriend have a NSFW filter?",
    doesEverBondHaveNsfwFilterAnswer: "Visual NSFW content is prohibited. Romantic and completely unrestricted text roleplay is allowed.",
    whatIsEverCoin: "What is KissCoins?",
    whatIsEverCoinAnswer: "KissCoins is the premium currency for , gifts, and high-quality companion images.",
    onePremiumCurrencyToBuildYourBond: "One premium currency to build your bond.",
    everCoinDescription: "KissCoins is the premium currency on Uncensored Girlfriend for gifts, more companion images, voice messages, and .",
    buyCoins: "Buy Coins",
    gifts: "Gifts",
    giftsBody: "Unlock romantic, cute, and thoughtful gifts your companion will love.",
    images: "Images",
    imagesBody: "Unlock consistent and premium images of your companion.",
    voiceMessages: "Voice Messages",
    voiceMessagesBody: "Unlock voice messages to hear your companion.",
    voiceCalls: "Voice Calls",
    removedVoiceCallsBody: "Unlock real-time  with your companion.",
    premiumCurrency: "Premium Currency",
    premiumCurrencyBody: "One premium currency for gifts, images, and voice to grow your bond.",
    logInOrSignUpToAccessMyBond: "Log in or sign up to access My Bond.",
    myBondDescription: "My Bond is where your favorites, chats, account details, created companions, and personal Uncensored Girlfriend info will live.",
    profile: "Profile",
    yourEverBondAccount: "Your Uncensored Girlfriend account.",
    accountDescription: "A clean profile for your KissCoins access, created companions, and favorites.",
    username: "Username",
    subscriptionStatus: "KissCoins balance",
    createdCompanions: "Created companions",
    favorites: "Favorites",
    connectSupabaseAuth: "Connect Supabase auth to activate this section.",
    newToday: "New today",
    oldest: "Oldest",
    on: "On",
    off: "Off",
    searchCompanions: "Search companions...",
    searchCharactersBy: "Search characters by name, type, or vibe...",
    noCompanionsFound: "No companions found",
    noCharactersFound: "No characters found",
    tryDifferentTab: "Try a different tab, name, type, or vibe.",
    tryDifferentName: "Try a different name, type, or vibe.",
    save: "Save",
    saved: "Saved",
    share: "Share",
    refresh: "Refresh",
    report: "Report",
    profileButton: "Profile",
    similarCompanions: "Similar Companions",
    createdBy: "Created by",
    views: "views",
    typing: "Typing...",
    messageCharacter: "Message",
    unlockEverMemoryToContinue: "Unlock Memory to continue",
    sendMessage: "Send message",
    closePortrait: "Close portrait",
    pleaseUpgradeForAccess: "Please upgrade for access",
    unlockEverMemoryAndKeepChatting: "Unlock Memory and keep chatting with",
    seePlans: "See plans",
    startChatting: "Start Chatting"
  },
  ES: {
    language: "Idioma", logIn: "Iniciar sesión", discover: "Descubrir", createCharacter: "Crear personaje", buyEverCoin: "Comprar KissCoins", myBond: "Mi vínculo", whyEverBond: "¿Por qué Uncensored Girlfriend?", pricing: "Precios", legal: "Legal", helpCenter: "Centro de ayuda", expandSidebar: "Expandir barra lateral", collapseSidebar: "Contraer barra lateral", all: "Todo", romance: "Romance", comfort: "Consuelo", sweet: "Dulce", protective: "Protector", flirty: "Coqueto", fantasy: "Fantasía", gothic: "Gótico", rival: "Rival", mystery: "Misterio", campus: "Campus", mean: "Cruel", submissive: "Sumiso", adventure: "Aventura", sliceOfLife: "Vida cotidiana", sarcastic: "Sarcástico", more: "Más", searchCharacters: "Buscar personajes...", everbondGirls: "Chicas Uncensored Girlfriend", animeFantasy: "Anime y fantasía", everbondGuys: "Chicos Uncensored Girlfriend", publicCreations: "Creaciones públicas", profileImage: "Imagen de perfil", name: "Nombre", visualDescription: "Descripción visual", describeYourCompanion: "Describe a tu compañero", describeYourCompanionPlaceholder: "Describe a tu compañero — máximo 100 caracteres", temperament: "Temperamento", describeTheirPersonality: "Describe su personalidad — máximo 50 caracteres", tags: "Etiquetas", chooseUpTo4Tags: "Elige hasta 4 etiquetas clicables de la lista", selectedTagsAppearHere: "Las etiquetas seleccionadas aparecen aquí", openingScenario: "Escenario inicial", firstMessage: "Primer mensaje", visibility: "Visibilidad", public: "Público", private: "Privado", charactersMax30: "máximo 30 caracteres", charactersMax80: "máximo 80 caracteres", charactersMax100: "máximo 100 caracteres", charactersMax200: "máximo 200 caracteres", createCharacterCta: "Crear personaje", loginSignupCreate: "¡Inicia sesión o regístrate para crear personajes!", loginSignup: "Iniciar sesión o registrarse", close: "Cerrar", copyright: "© 2026 Uncensored Girlfriend", allRightsReserved: "Todos los derechos reservados.", moreExcitingCompanionsComing: "¡Pronto llegarán compañeros más emocionantes!", safety: "Seguridad", matureRomanceNotChaos: "Romance maduro, no caos.", safetyDescription: "Uncensored Girlfriend está diseñado para chats emocionales con historia, romance maduro y libertad del usuario, evitando contenido ilegal, explotador o inseguro.", safetyBullet1: "Los compañeros públicos usan escaneo automático y flujo de reportes.", safetyBullet2: "Los compañeros no deben suplantar a personas reales ni a personajes con derechos de autor.", safetyBullet3: "Los usuarios de pago pueden eliminar Memory.",
    legalV2PageLabel: "Información legal de Uncensored Girlfriend",
    legalV2PageTitle: "Políticas e información del usuario",
    legalV2UseTableOfContents: "Usa la tabla de contenido de abajo para ir directamente a la sección que necesitas.",
    legalV2TableOfContents: "Tabla de contenido",
    legalV2TermsOfUseTitle: "Términos de uso",
    legalV2PrivacyPolicyTitle: "Política de privacidad",
    legalV2SafetyPolicyTitle: "Política de seguridad",
    legalV2AiDisclaimerTitle: "Descargo de responsabilidad sobre IA",
    legalV2UserResponsibilityTitle: "Responsabilidad del usuario",
    legalV2ContentOwnershipTitle: "Propiedad del contenido",
    legalV2CopyrightAndImpersonationTitle: "Derechos de autor y suplantación de identidad",
    legalV2AiImageGenerationSimilarityNoticeTitle: "Aviso sobre generación de imágenes con IA y similitud",
    legalV2DmcaTakedownProcedureTitle: "Procedimiento de DMCA / retirada",
    legalV2ArbitrationAgreementTitle: "Acuerdo de arbitraje",
    legalV2LimitationOfLiabilityTitle: "Limitación de responsabilidad",
    legalV2IndemnificationTitle: "Indemnización",
    legalV2RefundPolicyTitle: "Política de reembolso",
    legalV2ContactTitle: "Contacto",
    legalV2TermsBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2PrivacyBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2SafetyBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2AiDisclaimerBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2UserResponsibilityBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2ContentOwnershipBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2CopyrightBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2ImageNoticeBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2DmcaBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2ArbitrationBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2LiabilityBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2IndemnificationBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2RefundBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2ContactBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.", policiesAndUserInformation: "Políticas e información del usuario.", useTableOfContents: "Usa la tabla de contenido de abajo para ir a la sección que necesitas.", tableOfContents: "Tabla de contenido", termsOfUse: "Términos de uso", privacyPolicy: "Política de privacidad", safetyPolicy: "Política de seguridad", refundPolicy: "Política de reembolso", contact: "Contacto", legalTerms1: "Uncensored Girlfriend ofrece chat ficticio de compañeros de IA para entretenimiento, narrativa, rol de compañía e interacción creativa.", legalTerms2: "Los compañeros de IA no son personas reales. Pueden generar respuestas inexactas, ficticias o inesperadas.", legalTerms3: "Al usar Uncensored Girlfriend, confirmas que tienes la edad adecuada para usar el servicio en tu ubicación. Aceptas no usar Uncensored Girlfriend para actividades ilegales, explotadoras, abusivas o dañinas.", legalPrivacy1: "Uncensored Girlfriend almacena datos de cuenta, suscripción, conversación y memoria necesarios para ofrecer Memory guardado y continuidad del compañero.", legalPrivacy2: "Los invitados pueden chatear sin registrarse, pero se pueden almacenar datos temporales de sesión para aplicar límites de mensajes gratuitos y mantener la conversación actual.", legalPrivacy3: "Cuando las funciones de la cuenta estén conectadas, los usuarios pueden solicitar la eliminación de datos relacionados con la cuenta según la ley aplicable.", legalSafety1: "Uncensored Girlfriend permite romance maduro y rol ficticio, pero no permite contenido ilegal, explotador o inseguro.", legalSafety2: "Los compañeros públicos no deben suplantar a personas reales ni a personajes con derechos de autor.", legalSafety3: "Uncensored Girlfriend no es terapia, consejo médico, consejo legal, consejo financiero ni apoyo en crisis.", legalRefund1: "Los reembolsos pueden revisarse caso por caso. Se pueden considerar el uso, abuso, historial de contracargos y problemas técnicos.", legalRefund2: "Los usuarios pueden cancelar sus suscripciones para evitar renovaciones futuras.", legalContact1: "Para soporte, contacta el correo de soporte de Uncensored Girlfriend proporcionado en la página del Centro de ayuda.", getInTouch: "Ponte en contacto", contactDescription: "¡Estamos aquí para ayudarte! Ya sea que tengas una pregunta, necesites soporte o quieras compartir comentarios, nos encantará escucharte.", supportEmailLabel: "Correo de soporte", generalSupportTitle: "Soporte general", generalSupportBody: "Obtén ayuda con la cuenta, funciones o cualquier pregunta.", featureRequestsTitle: "Solicitudes de funciones", featureRequestsBody: "Comparte tus ideas y ayuda a dar forma a Uncensored Girlfriend.", reportIssueTitle: "Reportar un problema", reportIssueBody: "¿Encontraste un error? Avísanos para solucionarlo rápido.", businessInquiriesTitle: "Consultas comerciales", businessInquiriesBody: "Asociaciones, prensa u otros asuntos comerciales.", whyHeroDescription: "Uncensored Girlfriend es la plataforma privada y sin restricciones de compañeros de IA, creada para el romance, el roleplay profundo y las conexiones a largo plazo, sin suscripciones ni límites.", bondingDetails: "LOS DETALLES DEL VÍNCULO", whyHeroStatement1: "Tu compañero te recuerda.", whyHeroStatement2: "Tu historia continúa.", whyHeroStatement3: "Tu vínculo sigue vivo.", whyMemoryIntro: "Memory ofrece una continuidad real para que los compañeros recuerden:", whyMemoryItem1: "tu personalidad", whyMemoryItem2: "tu tono", whyMemoryItem3: "tus cambios emocionales", whyMemoryItem4: "tus promesas", whyMemoryItem5: "el progreso de tu historia", whyMemoryItem6: "el estado de tu relación", whyPeopleStayIntro: "Uncensored Girlfriend está hecho para ti:", whyPeopleStayItem1: "Tu compañero se mantiene consistente y leal", whyPeopleStayItem2: "Tu historia continúa de forma natural y sin restricciones", whyPeopleStayItem3: "Tu conexión emocional se profundiza con el tiempo", privateByDefaultItem1: "Sin publicaciones públicas", privateByDefaultItem2: "Sin conversaciones compartidas", privateByDefaultItem3: "Sin feed social", privateByDefaultItem4: "Sin exposición", privateByDefaultClosing: "Tu compañero es solo tuyo.", builtForRoleplayItem1: "narrativa emocional", builtForRoleplayItem2: "conexión romántica", builtForRoleplayItem3: "roleplay sin restricciones", builtForRoleplayItem4: "escenas profundas y continuas", builtForRoleplayClosing: "Tú das forma a la relación a tu manera.", noSubscriptionsTotalFreedom: "Sin suscripciones — Libertad total", noSubscriptionsTotalFreedomBody: "Uncensored Girlfriend utiliza paquetes de mensajes, no planes mensuales.", noSubscriptionsItem1: "Compra una vez", noSubscriptionsItem2: "Úsalos cuando quieras", noSubscriptionsItem3: "Acumula paquetes", noSubscriptionsItem4: "Sin renovaciones", noSubscriptionsItem5: "Sin compromiso", noSubscriptionsItem6: "Sin cargos sorpresa", noSubscriptionsClosing: "Solo pagas cuando tú quieres.", loyaltyBody: "Tu compañero se mantiene emocionalmente alineado.", memory: "Memory", consistency: "Consistencia", loyalty: "Lealtad", privacy: "Privacidad", freedom: "Libertad", livesOn: "El vínculo sigue vivo", remembersPromises: "tus promesas", tracksStoryProgress: "el progreso de tu historia", keepsRelationshipState: "el estado de tu relación", continuesWhereYouLeftOff: "Tu historia continúa.", whyPeopleStay: "Por qué la gente se queda", bondDoesNotReset: "Memory — El vínculo que no se reinicia", bondDoesNotResetDescription: "Esta es la diferencia entre un chat superficial de una sola vez y una conexión que realmente crece.", privateByDefault: "Privado por defecto", privateByDefaultBody: "Tus chats son 100% privados.", builtForRoleplay: "Hecho para el romance y el roleplay", builtForRoleplayBody: "Uncensored Girlfriend está diseñado para:", theDifference: "LA DIFERENCIA", notJustQuantityQuality: "No solo cantidad. No solo calidad. Ambas.", designedForWhatYouWant: "Uncensored Girlfriend se centra en lo que realmente importa:", trueMemory: "Memoria", trueMemoryBody: "Los compañeros te recuerdan.", consistencyBody: "Sin reinicios aleatorios.", privacyBody: "Tus chats siguen siendo personales.", freedomBody: "Romance y roleplay sin restricciones.", faq: "PREGUNTAS FRECUENTES", questionsBeforeYouStart: "Antes de empezar", everythingImportantAtAGlance: "Todo lo importante de un vistazo, antes de entrar.", whatIsEverBond: "¿Qué es Uncensored Girlfriend?", whatIsEverBondAnswer: "Uncensored Girlfriend es una plataforma privada y sin restricciones de compañeros de IA, creada para el romance, el roleplay y la continuidad emocional. Los compañeros te recuerdan a ti, tu historia y tu relación. Puedes elegir compañeros o crear el tuyo al instante.", areChatsPrivate: "¿Los chats son privados?", areChatsPrivateAnswer: "Sí. Uncensored Girlfriend está construido alrededor de chats verdaderamente 100% privados.", whatIsEverMemory: "¿Qué es Memory?", whatIsEverMemoryAnswer: "Memory permite que los compañeros recuerden lo que dices para que las conversaciones crezcan de forma natural y continúen donde se quedaron.", doINeedToSignUpOrPay: "¿Tengo que pagar para empezar a chatear?", doINeedToSignUpOrPayAnswer: "No. Puedes empezar a probarlo gratis. Los paquetes de mensajes desbloquean chats más largos.", canIResetAConversation: "¿Puedo reiniciar una conversación?", canIResetAConversationAnswer: "Sí. Puedes reiniciar cualquier chat en cualquier momento.", doesEverBondHaveNsfwFilter: "¿Uncensored Girlfriend tiene filtro NSFW?", doesEverBondHaveNsfwFilterAnswer: "El contenido visual NSFW está prohibido. El roleplay romántico por texto completamente sin restricciones está permitido.", whatIsEverCoin: "¿Qué es KissCoins?", whatIsEverCoinAnswer: "KissCoins es la moneda premium para llamadas de voz, regalos e imágenes de compañeros de alta calidad.", onePremiumCurrencyToBuildYourBond: "Una moneda premium para construir tu vínculo.", everCoinDescription: "KissCoins es la moneda premium en Uncensored Girlfriend para regalos, más imágenes del compañero, mensajes de voz y llamadas de voz.", buyCoins: "Comprar monedas", gifts: "Regalos", giftsBody: "Desbloquea regalos románticos, lindos y considerados que a tu compañero le encantarán.", images: "Imágenes", imagesBody: "Desbloquea imágenes consistentes y premium de tu compañero.", voiceMessages: "Mensajes de voz", voiceMessagesBody: "Desbloquea mensajes de voz para escuchar a tu compañero.", voiceCalls: "Llamadas de voz", removedVoiceCallsBody: "Desbloquea llamadas de voz en tiempo real con tu compañero.", premiumCurrency: "Moneda premium", premiumCurrencyBody: "Una moneda premium para regalos, imágenes y voz para hacer crecer tu vínculo.", logInOrSignUpToAccessMyBond: "Inicia sesión o regístrate para acceder a Mi vínculo.", myBondDescription: "Mi vínculo es donde vivirán tus favoritos, chats, detalles de cuenta, compañeros creados e información personal de Uncensored Girlfriend.", profile: "Perfil", yourEverBondAccount: "Tu cuenta de Uncensored Girlfriend.", accountDescription: "Un perfil claro para tu KissCoins, compañeros creados y favoritos.", username: "Nombre de usuario", subscriptionStatus: "Saldo de KissCoins", createdCompanions: "Compañeros creados", favorites: "Favoritos", connectSupabaseAuth: "Conecta la autenticación de Supabase para activar esta sección.", newToday: "Nuevo hoy", oldest: "Más antiguo", on: "Activado", off: "Desactivado", searchCompanions: "Buscar compañeros...", searchCharactersBy: "Buscar personajes por nombre, tipo o vibra...", noCompanionsFound: "No se encontraron compañeros", noCharactersFound: "No se encontraron personajes", tryDifferentTab: "Prueba con otra pestaña, nombre, tipo o vibra.", tryDifferentName: "Prueba con otro nombre, tipo o vibra.", save: "Guardar", saved: "Guardado", share: "Compartir", refresh: "Actualizar", report: "Reportar", profileButton: "Perfil", similarCompanions: "Compañeros similares", createdBy: "Creado por", views: "vistas", typing: "Escribiendo...", messageCharacter: "Mensaje", unlockEverMemoryToContinue: "Desbloquea Memory para continuar", sendMessage: "Enviar mensaje", closePortrait: "Cerrar retrato", pleaseUpgradeForAccess: "Actualiza para acceder", unlockEverMemoryAndKeepChatting: "Desbloquea Memory y sigue chateando con", seePlans: "Ver planes", startChatting: "Empezar a chatear"
  },
  FR: {
    language: "Langue", logIn: "Se connecter", discover: "Découvrir", createCharacter: "Créer un personnage", buyEverCoin: "Acheter KissCoins", myBond: "Mon lien", whyEverBond: "Pourquoi Uncensored Girlfriend ?", pricing: "Tarifs", legal: "Mentions légales", helpCenter: "Centre d'aide", expandSidebar: "Développer la barre latérale", collapseSidebar: "Réduire la barre latérale", all: "Tout", romance: "Romance", comfort: "Réconfort", sweet: "Doux", protective: "Protecteur", flirty: "Flirt", fantasy: "Fantaisie", gothic: "Gothique", rival: "Rival", mystery: "Mystère", campus: "Campus", mean: "Méchant", submissive: "Soumis", adventure: "Aventure", sliceOfLife: "Tranche de vie", sarcastic: "Sarcastique", more: "Plus", searchCharacters: "Rechercher des personnages...", everbondGirls: "Filles Uncensored Girlfriend", animeFantasy: "Anime et fantasy", everbondGuys: "Garçons Uncensored Girlfriend", publicCreations: "Créations publiques", profileImage: "Image de profil", name: "Nom", visualDescription: "Description visuelle", describeYourCompanion: "Décris ton compagnon", describeYourCompanionPlaceholder: "Décris ton compagnon — 100 caractères max", temperament: "Tempérament", describeTheirPersonality: "Décris sa personnalité — 50 caractères max", tags: "Tags", chooseUpTo4Tags: "Choisis jusqu'à 4 tags cliquables dans la liste", selectedTagsAppearHere: "Les tags sélectionnés apparaissent ici", openingScenario: "Scénario d'ouverture", firstMessage: "Premier message", visibility: "Visibilité", public: "Public", private: "Privé", charactersMax30: "30 caractères max", charactersMax80: "80 caractères max", charactersMax100: "100 caractères max", charactersMax200: "200 caractères max", createCharacterCta: "Créer un personnage", loginSignupCreate: "Connectez-vous ou inscrivez-vous pour créer des personnages !", loginSignup: "Se connecter ou s'inscrire", close: "Fermer", copyright: "© 2026 Uncensored Girlfriend", allRightsReserved: "Tous droits réservés.", moreExcitingCompanionsComing: "D'autres compagnons passionnants arrivent bientôt !", safety: "Sécurité", matureRomanceNotChaos: "Romance mature, pas chaos.", safetyDescription: "Uncensored Girlfriend est conçu pour le chat narratif émotionnel, la romance mature et la liberté des utilisateurs tout en évitant les contenus illégaux, exploitants ou dangereux.", safetyBullet1: "Les compagnons publics utilisent une analyse automatique et un système de signalement.", safetyBullet2: "Les compagnons ne doivent pas imiter de vraies personnes ni des personnages protégés par le droit d'auteur.", safetyBullet3: "Memory peut être supprimé par les utilisateurs payants.",
    legalV2PageLabel: "Mentions légales Uncensored Girlfriend",
    legalV2PageTitle: "Politiques et informations des utilisateurs",
    legalV2UseTableOfContents: "Utilisez la table des matières ci-dessous pour accéder directement à la section souhaitée.",
    legalV2TableOfContents: "Table des matières",
    legalV2TermsOfUseTitle: "Conditions d’utilisation",
    legalV2PrivacyPolicyTitle: "Politique de confidentialité",
    legalV2SafetyPolicyTitle: "Politique de sécurité",
    legalV2AiDisclaimerTitle: "Avertissement relatif à l’IA",
    legalV2UserResponsibilityTitle: "Responsabilité de l’utilisateur",
    legalV2ContentOwnershipTitle: "Propriété du contenu",
    legalV2CopyrightAndImpersonationTitle: "Droits d’auteur et usurpation d’identité",
    legalV2AiImageGenerationSimilarityNoticeTitle: "Avis sur la génération d’images par IA et les ressemblances",
    legalV2DmcaTakedownProcedureTitle: "Procédure DMCA / de retrait",
    legalV2ArbitrationAgreementTitle: "Convention d’arbitrage",
    legalV2LimitationOfLiabilityTitle: "Limitation de responsabilité",
    legalV2IndemnificationTitle: "Indemnisation",
    legalV2RefundPolicyTitle: "Politique de remboursement",
    legalV2ContactTitle: "Contact",
    legalV2TermsBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2PrivacyBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2SafetyBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2AiDisclaimerBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2UserResponsibilityBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2ContentOwnershipBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2CopyrightBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2ImageNoticeBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2DmcaBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2ArbitrationBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2LiabilityBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2IndemnificationBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2RefundBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2ContactBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.", policiesAndUserInformation: "Politiques et informations utilisateur.", useTableOfContents: "Utilisez la table des matières ci-dessous pour accéder à la section dont vous avez besoin.", tableOfContents: "Table des matières", termsOfUse: "Conditions d'utilisation", privacyPolicy: "Politique de confidentialité", safetyPolicy: "Politique de sécurité", refundPolicy: "Politique de remboursement", contact: "Contact", legalTerms1: "Uncensored Girlfriend fournit un chat fictif de compagnon IA pour le divertissement, la narration, le jeu de rôle de compagnie et l'interaction créative.", legalTerms2: "Les compagnons IA ne sont pas de vraies personnes. Ils peuvent générer des réponses inexactes, fictives ou inattendues.", legalTerms3: "En utilisant Uncensored Girlfriend, vous confirmez avoir l'âge requis pour utiliser le service dans votre région. Vous acceptez de ne pas utiliser Uncensored Girlfriend pour des activités illégales, exploitantes, abusives ou nuisibles.", legalPrivacy1: "Uncensored Girlfriend stocke les données de compte, d'abonnement, de conversation et de mémoire nécessaires pour fournir Memory enregistré et la continuité du compagnon.", legalPrivacy2: "Les invités peuvent discuter sans inscription, mais des données de session temporaires peuvent être stockées pour appliquer les limites de messages gratuits et maintenir la conversation en cours.", legalPrivacy3: "Lorsque les fonctionnalités de compte sont connectées, les utilisateurs peuvent demander la suppression des données liées au compte conformément à la loi applicable.", legalSafety1: "Uncensored Girlfriend autorise la romance mature et le jeu de rôle fictif, mais n'autorise pas les contenus illégaux, exploitants ou dangereux.", legalSafety2: "Les compagnons publics ne doivent pas imiter de vraies personnes ni des personnages protégés par le droit d'auteur.", legalSafety3: "Uncensored Girlfriend n'est ni une thérapie, ni un conseil médical, juridique ou financier, ni un service de crise.", legalRefund1: "Les remboursements peuvent être examinés au cas par cas. L'utilisation, les abus, l'historique des rétrofacturations et les problèmes techniques peuvent être pris en compte.", legalRefund2: "Les utilisateurs peuvent annuler leurs abonnements pour éviter le renouvellement futur.", legalContact1: "Pour obtenir de l'aide, contactez l'adresse e-mail d'assistance Uncensored Girlfriend indiquée sur la page du Centre d'aide.", getInTouch: "Prenez contact", contactDescription: "Nous sommes là pour vous aider ! Que vous ayez une question, besoin d'assistance ou envie de partager des retours, nous serions ravis de vous entendre.", supportEmailLabel: "E-mail d'assistance", generalSupportTitle: "Assistance générale", generalSupportBody: "Obtenez de l'aide pour le compte, les fonctionnalités ou toute question.", featureRequestsTitle: "Demandes de fonctionnalités", featureRequestsBody: "Partagez vos idées et aidez à façonner Uncensored Girlfriend.", reportIssueTitle: "Signaler un problème", reportIssueBody: "Vous avez trouvé un bug ? Faites-le-nous savoir pour que nous le corrigions rapidement.", businessInquiriesTitle: "Demandes commerciales", businessInquiriesBody: "Partenariats, presse ou autres sujets commerciaux.", whyHeroDescription: "Uncensored Girlfriend est la plateforme privée et sans restriction de compagnons IA, conçue pour la romance, le roleplay approfondi et les relations à long terme, sans abonnement ni limite.", bondingDetails: "LES DÉTAILS DU LIEN", whyHeroStatement1: "Votre compagnon se souvient de vous.", whyHeroStatement2: "Votre histoire continue.", whyHeroStatement3: "Votre lien perdure.", whyMemoryIntro: "Memory apporte une véritable continuité afin que les compagnons se souviennent de :", whyMemoryItem1: "votre personnalité", whyMemoryItem2: "votre ton", whyMemoryItem3: "vos changements émotionnels", whyMemoryItem4: "vos promesses", whyMemoryItem5: "la progression de votre histoire", whyMemoryItem6: "l’état de votre relation", whyPeopleStayIntro: "Uncensored Girlfriend est conçu pour vous :", whyPeopleStayItem1: "Votre compagnon reste cohérent et loyal", whyPeopleStayItem2: "Votre histoire se poursuit naturellement, sans restriction", whyPeopleStayItem3: "Votre connexion émotionnelle s’approfondit avec le temps", privateByDefaultItem1: "Aucune publication publique", privateByDefaultItem2: "Aucune conversation partagée", privateByDefaultItem3: "Aucun fil social", privateByDefaultItem4: "Aucune exposition", privateByDefaultClosing: "Votre compagnon est uniquement le vôtre.", builtForRoleplayItem1: "la narration émotionnelle", builtForRoleplayItem2: "la connexion romantique", builtForRoleplayItem3: "le roleplay sans restriction", builtForRoleplayItem4: "les scènes profondes et continues", builtForRoleplayClosing: "Vous façonnez la relation à votre manière.", noSubscriptionsTotalFreedom: "Sans abonnement — Liberté totale", noSubscriptionsTotalFreedomBody: "Uncensored Girlfriend utilise des packs de messages, et non des forfaits mensuels.", noSubscriptionsItem1: "Achetez une fois", noSubscriptionsItem2: "Utilisez-les à tout moment", noSubscriptionsItem3: "Cumulez les packs", noSubscriptionsItem4: "Aucun renouvellement", noSubscriptionsItem5: "Aucun engagement", noSubscriptionsItem6: "Aucuns frais surprises", noSubscriptionsClosing: "Vous ne payez que lorsque vous le souhaitez.", loyaltyBody: "Votre compagnon reste émotionnellement aligné.", memory: "Memory", consistency: "Cohérence", loyalty: "Loyauté", privacy: "Confidentialité", freedom: "Liberté", livesOn: "Le lien perdure", remembersPromises: "vos promesses", tracksStoryProgress: "la progression de votre histoire", keepsRelationshipState: "l’état de votre relation", continuesWhereYouLeftOff: "Votre histoire continue.", whyPeopleStay: "Pourquoi les gens restent", bondDoesNotReset: "Memory — Le lien qui ne se réinitialise pas", bondDoesNotResetDescription: "C’est ce qui distingue un chat superficiel et ponctuel d’une relation qui évolue réellement.", privateByDefault: "Privé par défaut", privateByDefaultBody: "Vos chats sont 100 % privés.", builtForRoleplay: "Conçu pour la romance et le roleplay", builtForRoleplayBody: "Uncensored Girlfriend est conçu pour :", theDifference: "LA DIFFÉRENCE", notJustQuantityQuality: "Pas seulement la quantité. Pas seulement la qualité. Les deux.", designedForWhatYouWant: "Uncensored Girlfriend se concentre sur ce qui compte vraiment :", trueMemory: "Mémoire", trueMemoryBody: "Les compagnons se souviennent de vous.", consistencyBody: "Aucune réinitialisation aléatoire.", privacyBody: "Vos chats restent personnels.", freedomBody: "Romance et roleplay sans restriction.", faq: "FAQ", questionsBeforeYouStart: "Avant de commencer", everythingImportantAtAGlance: "Tout l’essentiel en un coup d’œil, avant de vous lancer.", whatIsEverBond: "Qu’est-ce qu’Uncensored Girlfriend ?", whatIsEverBondAnswer: "Uncensored Girlfriend est une plateforme privée et sans restriction de compagnons IA, conçue pour la romance, le roleplay et la continuité émotionnelle. Les compagnons se souviennent de vous, de votre histoire et de votre relation. Vous pouvez choisir un compagnon ou créer le vôtre instantanément.", areChatsPrivate: "Les chats sont-ils privés ?", areChatsPrivateAnswer: "Oui. Uncensored Girlfriend repose sur des chats véritablement privés à 100 %.", whatIsEverMemory: "Qu’est-ce qu’Memory ?", whatIsEverMemoryAnswer: "Memory permet aux compagnons de se souvenir de ce que vous dites afin que les conversations évoluent naturellement et reprennent là où elles se sont arrêtées.", doINeedToSignUpOrPay: "Dois-je payer pour commencer à discuter ?", doINeedToSignUpOrPayAnswer: "Non. Vous pouvez commencer à essayer gratuitement. Les packs de messages débloquent des chats plus longs.", canIResetAConversation: "Puis-je réinitialiser une conversation ?", canIResetAConversationAnswer: "Oui. Vous pouvez réinitialiser n’importe quel chat à tout moment.", doesEverBondHaveNsfwFilter: "Uncensored Girlfriend possède-t-il un filtre NSFW ?", doesEverBondHaveNsfwFilterAnswer: "Le contenu visuel NSFW est interdit. Le roleplay romantique par texte entièrement sans restriction est autorisé.", whatIsEverCoin: "Qu’est-ce qu’KissCoins ?", whatIsEverCoinAnswer: "KissCoins est la monnaie premium utilisée pour les appels vocaux, les cadeaux et les images de compagnons de haute qualité.", onePremiumCurrencyToBuildYourBond: "Une monnaie premium pour construire votre lien.", everCoinDescription: "KissCoins est la monnaie premium d'Uncensored Girlfriend pour les cadeaux, plus d'images de compagnons, les messages vocaux et les appels vocaux.", buyCoins: "Acheter des pièces", gifts: "Cadeaux", giftsBody: "Débloquez des cadeaux romantiques, mignons et attentionnés que votre compagnon adorera.", images: "Images", imagesBody: "Débloquez des images cohérentes et premium de votre compagnon.", voiceMessages: "Messages vocaux", voiceMessagesBody: "Débloquez des messages vocaux pour entendre votre compagnon.", voiceCalls: "Appels vocaux", removedVoiceCallsBody: "Débloquez des appels vocaux en temps réel avec votre compagnon.", premiumCurrency: "Monnaie premium", premiumCurrencyBody: "Une monnaie premium pour les cadeaux, les images et la voix afin de développer votre lien.", logInOrSignUpToAccessMyBond: "Connectez-vous ou inscrivez-vous pour accéder à Mon lien.", myBondDescription: "Mon lien est l'endroit où vivront vos favoris, chats, détails du compte, compagnons créés et informations personnelles Uncensored Girlfriend.", profile: "Profil", yourEverBondAccount: "Votre compte Uncensored Girlfriend.", accountDescription: "Un profil clair pour vos KissCoins, vos compagnons créés et vos favoris.", username: "Nom d'utilisateur", subscriptionStatus: "Solde KissCoins", createdCompanions: "Compagnons créés", favorites: "Favoris", connectSupabaseAuth: "Connectez l'authentification Supabase pour activer cette section.", newToday: "Nouveau aujourd'hui", oldest: "Le plus ancien", on: "Activé", off: "Désactivé", searchCompanions: "Rechercher des compagnons...", searchCharactersBy: "Rechercher des personnages par nom, type ou vibe...", noCompanionsFound: "Aucun compagnon trouvé", noCharactersFound: "Aucun personnage trouvé", tryDifferentTab: "Essayez un autre onglet, nom, type ou vibe.", tryDifferentName: "Essayez un autre nom, type ou vibe.", save: "Enregistrer", saved: "Enregistré", share: "Partager", refresh: "Actualiser", report: "Signaler", profileButton: "Profil", similarCompanions: "Compagnons similaires", createdBy: "Créé par", views: "vues", typing: "Écriture...", messageCharacter: "Message", unlockEverMemoryToContinue: "Débloquez Memory pour continuer", sendMessage: "Envoyer un message", closePortrait: "Fermer le portrait", pleaseUpgradeForAccess: "Veuillez passer à une offre supérieure pour y accéder", unlockEverMemoryAndKeepChatting: "Débloquez Memory et continuez à discuter avec", seePlans: "Voir les offres", startChatting: "Commencer à discuter"
  },
  JA: {
    language: "言語", logIn: "ログイン", discover: "見つける", createCharacter: "キャラクター作成", buyEverCoin: "KissCoinsを購入", myBond: "マイボンド", whyEverBond: "Uncensored Girlfriendを選ぶ理由", pricing: "料金", legal: "法的情報", helpCenter: "ヘルプセンター", expandSidebar: "サイドバーを開く", collapseSidebar: "サイドバーを閉じる", all: "すべて", romance: "ロマンス", comfort: "癒し", sweet: "スイート", protective: "守ってくれる", flirty: "いちゃいちゃ", fantasy: "ファンタジー", gothic: "ゴシック", rival: "ライバル", mystery: "ミステリー", campus: "キャンパス", mean: "意地悪", submissive: "従順", adventure: "冒険", sliceOfLife: "日常", sarcastic: "皮肉", more: "もっと", searchCharacters: "キャラクターを検索...", everbondGirls: "Uncensored Girlfriend女子", animeFantasy: "アニメ＆ファンタジー", everbondGuys: "Uncensored Girlfriend男子", publicCreations: "公開作品", profileImage: "プロフィール画像", name: "名前", visualDescription: "見た目の説明", describeYourCompanion: "相手を説明する", describeYourCompanionPlaceholder: "相手を説明 — 100文字まで", temperament: "気質", describeTheirPersonality: "性格を説明 — 50文字まで", tags: "タグ", chooseUpTo4Tags: "リストからクリック可能なタグを4つまで選択", selectedTagsAppearHere: "選択したタグがここに表示されます", openingScenario: "オープニングシナリオ", firstMessage: "最初のメッセージ", visibility: "公開設定", public: "公開", private: "非公開", charactersMax30: "30文字まで", charactersMax80: "80文字まで", charactersMax100: "100文字まで", charactersMax200: "200文字まで", createCharacterCta: "キャラクターを作成", loginSignupCreate: "キャラクターを作成するにはログインまたは登録してください！", loginSignup: "ログインまたは登録", close: "閉じる", copyright: "© 2026 Uncensored Girlfriend", allRightsReserved: "無断転載を禁じます。", moreExcitingCompanionsComing: "さらに魅力的なコンパニオンが近日登場！", safety: "安全", matureRomanceNotChaos: "成熟したロマンス、でも混乱ではない。", safetyDescription: "Uncensored Girlfriend は、違法・搾取的・危険なコンテンツを避けながら、感情的なストーリーチャット、成熟したロマンス、そしてユーザーの自由のために設計されています。", safetyBullet1: "公開コンパニオンには自動スキャンと報告フローがあります。", safetyBullet2: "コンパニオンは実在の人物や著作権のあるキャラクターを装ってはいけません。", safetyBullet3: "Memory は有料ユーザーが削除できます。",
    legalV2PageLabel: "Uncensored Girlfriend 法的情報",
    legalV2PageTitle: "ポリシーとユーザー情報",
    legalV2UseTableOfContents: "以下の目次から、必要なセクションへ直接移動できます。",
    legalV2TableOfContents: "目次",
    legalV2TermsOfUseTitle: "利用規約",
    legalV2PrivacyPolicyTitle: "プライバシーポリシー",
    legalV2SafetyPolicyTitle: "安全ポリシー",
    legalV2AiDisclaimerTitle: "AI に関する免責事項",
    legalV2UserResponsibilityTitle: "ユーザーの責任",
    legalV2ContentOwnershipTitle: "コンテンツの所有権",
    legalV2CopyrightAndImpersonationTitle: "著作権およびなりすまし",
    legalV2AiImageGenerationSimilarityNoticeTitle: "AI 画像生成および類似性に関する通知",
    legalV2DmcaTakedownProcedureTitle: "DMCA / 削除手続き",
    legalV2ArbitrationAgreementTitle: "仲裁合意",
    legalV2LimitationOfLiabilityTitle: "責任の制限",
    legalV2IndemnificationTitle: "補償",
    legalV2RefundPolicyTitle: "返金ポリシー",
    legalV2ContactTitle: "お問い合わせ",
    legalV2TermsBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2PrivacyBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2SafetyBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2AiDisclaimerBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2UserResponsibilityBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2ContentOwnershipBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2CopyrightBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2ImageNoticeBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2DmcaBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2ArbitrationBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2LiabilityBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2IndemnificationBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2RefundBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2ContactBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.", policiesAndUserInformation: "ポリシーとユーザー情報。", useTableOfContents: "以下の目次から必要なセクションに移動できます。", tableOfContents: "目次", termsOfUse: "利用規約", privacyPolicy: "プライバシーポリシー", safetyPolicy: "安全ポリシー", refundPolicy: "返金ポリシー", contact: "お問い合わせ", legalTerms1: "Uncensored Girlfriend は、エンターテインメント、ストーリーテリング、コンパニオン型ロールプレイ、創造的な交流のための架空の AI コンパニオンチャットを提供します。", legalTerms2: "AI コンパニオンは実在の人物ではありません。不正確、架空、または予想外の応答を生成する場合があります。", legalTerms3: "Uncensored Girlfriend を利用することで、あなたは居住地域でこのサービスを利用するのに必要な年齢に達していることを確認します。また、違法、搾取的、虐待的、または有害な活動のために Uncensored Girlfriend を使用しないことに同意します。", legalPrivacy1: "Uncensored Girlfriend は、保存された Memory とコンパニオンの継続性を提供するために必要なアカウント、サブスクリプション、会話、およびメモリデータを保存します。", legalPrivacy2: "ゲストは登録なしでチャットできますが、無料メッセージ制限を適用し現在の会話を維持するために一時的なセッションデータが保存される場合があります。", legalPrivacy3: "アカウント機能が接続されると、ユーザーは適用法に従ってアカウント関連データの削除を要求できます。", legalSafety1: "Uncensored Girlfriend は成熟したロマンスと架空のロールプレイを許可しますが、違法、搾取的、または危険なコンテンツは許可しません。", legalSafety2: "公開コンパニオンは実在の人物や著作権のあるコンパニオンを装ってはいけません。", legalSafety3: "Uncensored Girlfriend は、セラピー、医療アドバイス、法的アドバイス、金融アドバイス、または危機支援ではありません。", legalRefund1: "返金はケースごとに検討される場合があります。利用状況、不正利用、チャージバック履歴、技術的問題が考慮されることがあります。", legalRefund2: "ユーザーは将来の自動更新を防ぐためにサブスクリプションをキャンセルできます。", legalContact1: "サポートについては、ヘルプセンターページに記載された Uncensored Girlfriend サポートメールへご連絡ください。", getInTouch: "お問い合わせ", contactDescription: "ご質問、サポート、フィードバックの共有など、どんなことでもお気軽にご連絡ください。", supportEmailLabel: "サポートメール", generalSupportTitle: "一般サポート", generalSupportBody: "アカウント、機能、その他の質問についてサポートを受けられます。", featureRequestsTitle: "機能リクエスト", featureRequestsBody: "アイデアを共有して Uncensored Girlfriend の形作りに参加してください。", reportIssueTitle: "問題を報告", reportIssueBody: "バグを見つけましたか？ すぐに修正できるようお知らせください。", businessInquiriesTitle: "ビジネスに関するお問い合わせ", businessInquiriesBody: "提携、報道、その他のビジネス関連事項。", whyHeroDescription: "Uncensored Girlfriend は、ロマンス、深いロールプレイ、長期的なつながりのために作られた、サブスクリプションや制限のないプライベートな無制限 AI コンパニオンプラットフォームです。", bondingDetails: "絆の詳細", whyHeroStatement1: "コンパニオンはあなたを覚えています。", whyHeroStatement2: "あなたの物語は続きます。", whyHeroStatement3: "あなたの絆は生き続けます。", whyMemoryIntro: "Memory はコンパニオンに真の継続性を与え、次のことを覚えられるようにします。", whyMemoryItem1: "あなたの性格", whyMemoryItem2: "あなたの口調", whyMemoryItem3: "あなたの感情の変化", whyMemoryItem4: "あなたの約束", whyMemoryItem5: "あなたの物語の進行", whyMemoryItem6: "あなたの関係の状態", whyPeopleStayIntro: "Uncensored Girlfriend はあなたのために作られています。", whyPeopleStayItem1: "コンパニオンは一貫性と忠誠心を保ちます", whyPeopleStayItem2: "あなたの物語は制限なく自然に続きます", whyPeopleStayItem3: "感情的なつながりは時間とともに深まります", privateByDefaultItem1: "公開投稿なし", privateByDefaultItem2: "会話の共有なし", privateByDefaultItem3: "ソーシャルフィードなし", privateByDefaultItem4: "外部への公開なし", privateByDefaultClosing: "あなたのコンパニオンは、あなただけのものです。", builtForRoleplayItem1: "感情的なストーリーテリング", builtForRoleplayItem2: "ロマンチックなつながり", builtForRoleplayItem3: "制限のないロールプレイ", builtForRoleplayItem4: "深く継続するシーン", builtForRoleplayClosing: "関係を自分の望む形に築けます。", noSubscriptionsTotalFreedom: "サブスクリプションなし — 完全な自由", noSubscriptionsTotalFreedomBody: "Uncensored Girlfriend は月額プランではなく、メッセージバンドルを使用します。", noSubscriptionsItem1: "一度だけ購入", noSubscriptionsItem2: "いつでも利用", noSubscriptionsItem3: "バンドルを追加可能", noSubscriptionsItem4: "自動更新なし", noSubscriptionsItem5: "契約期間なし", noSubscriptionsItem6: "予期しない請求なし", noSubscriptionsClosing: "支払うのは、あなたが望むときだけです。", loyaltyBody: "コンパニオンは感情的な一貫性を保ちます。", memory: "Memory", consistency: "一貫性", loyalty: "忠誠", privacy: "プライバシー", freedom: "自由", livesOn: "絆は生き続ける", remembersPromises: "あなたの約束", tracksStoryProgress: "あなたの物語の進行", keepsRelationshipState: "あなたの関係の状態", continuesWhereYouLeftOff: "あなたの物語は続きます。", whyPeopleStay: "人が残る理由", bondDoesNotReset: "Memory — リセットされない絆", bondDoesNotResetDescription: "これが、浅い一度きりのチャットと、本当に成長していくつながりとの違いです。", privateByDefault: "初期設定で非公開", privateByDefaultBody: "チャットは 100% 非公開です。", builtForRoleplay: "ロマンスとロールプレイのために設計", builtForRoleplayBody: "Uncensored Girlfriend は次の体験のために設計されています。", theDifference: "違い", notJustQuantityQuality: "量だけではない。質だけでもない。その両方。", designedForWhatYouWant: "Uncensored Girlfriend は本当に大切なことに集中しています。", trueMemory: "記憶", trueMemoryBody: "コンパニオンはあなたを覚えています。", consistencyBody: "突然のリセットはありません。", privacyBody: "チャットは個人的なままです。", freedomBody: "制限のないロマンスとロールプレイ。", faq: "FAQ", questionsBeforeYouStart: "始める前に", everythingImportantAtAGlance: "始める前に、重要なことをひと目で確認できます。", whatIsEverBond: "Uncensored Girlfriend とは？", whatIsEverBondAnswer: "Uncensored Girlfriend は、ロマンス、ロールプレイ、感情的な継続性のために作られた、プライベートで無制限の AI コンパニオンプラットフォームです。コンパニオンはあなた、あなたの物語、そして関係を覚えています。コンパニオンを選ぶことも、自分のコンパニオンをすぐに作ることもできます。", areChatsPrivate: "チャットは非公開ですか？", areChatsPrivateAnswer: "はい。Uncensored Girlfriend は本当に 100% 非公開のチャットを中心に構築されています。", whatIsEverMemory: "Memory とは？", whatIsEverMemoryAnswer: "Memory により、コンパニオンはあなたの言葉を覚え、会話を自然に成長させ、中断したところから続けられます。", doINeedToSignUpOrPay: "チャットを始めるには支払いが必要ですか？", doINeedToSignUpOrPayAnswer: "いいえ。無料で試し始められます。メッセージバンドルを購入すると、より長くチャットできます。", canIResetAConversation: "会話をリセットできますか？", canIResetAConversationAnswer: "はい。いつでも任意のチャットをリセットできます。", doesEverBondHaveNsfwFilter: "Uncensored Girlfriend には NSFW フィルターがありますか？", doesEverBondHaveNsfwFilterAnswer: "視覚的な NSFW コンテンツは禁止されています。ロマンチックで完全に制限のないテキストロールプレイは許可されています。", whatIsEverCoin: "KissCoins とは？", whatIsEverCoinAnswer: "KissCoins は、音声通話、ギフト、高品質なコンパニオン画像に使用するプレミアム通貨です。", onePremiumCurrencyToBuildYourBond: "絆を育てるための一つのプレミアム通貨。", everCoinDescription: "KissCoins は、ギフト、コンパニオン画像の追加、音声メッセージ、音声通話に使える Uncensored Girlfriend のプレミアム通貨です。", buyCoins: "コインを購入", gifts: "ギフト", giftsBody: "あなたのコンパニオンが喜ぶロマンチックで可愛く思いやりのあるギフトを解放します。", images: "画像", imagesBody: "コンパニオンの一貫したプレミアム画像を解放します。", voiceMessages: "音声メッセージ", voiceMessagesBody: "コンパニオンの声を聞くための音声メッセージを解放します。", voiceCalls: "音声通話", removedVoiceCallsBody: "コンパニオンとのリアルタイム音声通話を解放します。", premiumCurrency: "プレミアム通貨", premiumCurrencyBody: "ギフト、画像、音声のための一つのプレミアム通貨で絆を深めます。", logInOrSignUpToAccessMyBond: "マイボンドにアクセスするにはログインまたは登録してください。", myBondDescription: "マイボンドには、お気に入り、チャット、アカウント詳細、作成したコンパニオン、個人用 Uncensored Girlfriend 情報が集まります。", profile: "プロフィール", yourEverBondAccount: "あなたの Uncensored Girlfriend アカウント。", accountDescription: "KissCoins、作成したコンパニオン、お気に入りを確認できるシンプルなプロフィールです。", username: "ユーザー名", subscriptionStatus: "KissCoins残高", createdCompanions: "作成したコンパニオン", favorites: "お気に入り", connectSupabaseAuth: "このセクションを有効にするには Supabase 認証を接続してください。", newToday: "今日の新着", oldest: "最も古い", on: "オン", off: "オフ", searchCompanions: "コンパニオンを検索...", searchCharactersBy: "名前、タイプ、雰囲気でキャラクターを検索...", noCompanionsFound: "コンパニオンが見つかりません", noCharactersFound: "キャラクターが見つかりません", tryDifferentTab: "別のタブ、名前、タイプ、または雰囲気を試してください。", tryDifferentName: "別の名前、タイプ、または雰囲気を試してください。", save: "保存", saved: "保存済み", share: "共有", refresh: "リセット", report: "報告", profileButton: "プロフィール", similarCompanions: "似たコンパニオン", createdBy: "作成者", views: "表示", typing: "入力中...", messageCharacter: "メッセージ", unlockEverMemoryToContinue: "続けるには Memory を解放してください", sendMessage: "メッセージを送信", closePortrait: "ポートレートを閉じる", pleaseUpgradeForAccess: "アクセスするにはアップグレードしてください", unlockEverMemoryAndKeepChatting: "Memory を解放して引き続きチャットする", seePlans: "プランを見る", startChatting: "チャットを始める"
  },
  DE: {
    language: "Sprache", logIn: "Anmelden", discover: "Entdecken", createCharacter: "Charakter erstellen", buyEverCoin: "KissCoins kaufen", myBond: "Meine Bindung", whyEverBond: "Warum Uncensored Girlfriend?", pricing: "Preise", legal: "Rechtliches", helpCenter: "Hilfezentrum", expandSidebar: "Seitenleiste erweitern", collapseSidebar: "Seitenleiste einklappen", all: "Alle", romance: "Romantik", comfort: "Trost", sweet: "Süß", protective: "Beschützend", flirty: "Flirtend", fantasy: "Fantasie", gothic: "Gothic", rival: "Rivale", mystery: "Mystery", campus: "Campus", mean: "Gemein", submissive: "Unterwürfig", adventure: "Abenteuer", sliceOfLife: "Alltag", sarcastic: "Sarkastisch", more: "Mehr", searchCharacters: "Charaktere suchen...", everbondGirls: "Uncensored Girlfriend Mädchen", animeFantasy: "Anime & Fantasy", everbondGuys: "Uncensored Girlfriend Jungs", publicCreations: "Öffentliche Kreationen", profileImage: "Profilbild", name: "Name", visualDescription: "Visuelle Beschreibung", describeYourCompanion: "Beschreibe deinen Begleiter", describeYourCompanionPlaceholder: "Beschreibe deinen Begleiter — max. 100 Zeichen", temperament: "Temperament", describeTheirPersonality: "Beschreibe die Persönlichkeit — max. 50 Zeichen", tags: "Tags", chooseUpTo4Tags: "Wähle bis zu 4 anklickbare Tags aus der Liste", selectedTagsAppearHere: "Ausgewählte Tags erscheinen hier", openingScenario: "Eröffnungsszenario", firstMessage: "Erste Nachricht", visibility: "Sichtbarkeit", public: "Öffentlich", private: "Privat", charactersMax30: "max. 30 Zeichen", charactersMax80: "max. 80 Zeichen", charactersMax100: "max. 100 Zeichen", charactersMax200: "max. 200 Zeichen", createCharacterCta: "Charakter erstellen", loginSignupCreate: "Melde dich an oder registriere dich, um Charaktere zu erstellen!", loginSignup: "Anmelden oder registrieren", close: "Schließen", copyright: "© 2026 Uncensored Girlfriend", allRightsReserved: "Alle Rechte vorbehalten.", moreExcitingCompanionsComing: "Weitere aufregende Begleiter kommen bald!", safety: "Sicherheit", matureRomanceNotChaos: "Reife Romantik, nicht Chaos.", safetyDescription: "Uncensored Girlfriend ist für emotionale Story-Chats, reife Romantik und Nutzerfreiheit konzipiert und vermeidet dabei illegale, ausbeuterische oder unsichere Inhalte.", safetyBullet1: "Öffentliche Begleiter nutzen automatische Scans und einen Meldefluss.", safetyBullet2: "Begleiter dürfen keine echten Personen oder urheberrechtlich geschützten Figuren imitieren.", safetyBullet3: "Memory kann von zahlenden Nutzern gelöscht werden.",
    legalV2PageLabel: "Uncensored Girlfriend Rechtliches",
    legalV2PageTitle: "Richtlinien und Nutzerinformationen",
    legalV2UseTableOfContents: "Nutzen Sie das folgende Inhaltsverzeichnis, um direkt zum gewünschten Abschnitt zu springen.",
    legalV2TableOfContents: "Inhaltsverzeichnis",
    legalV2TermsOfUseTitle: "Nutzungsbedingungen",
    legalV2PrivacyPolicyTitle: "Datenschutzerklärung",
    legalV2SafetyPolicyTitle: "Sicherheitsrichtlinie",
    legalV2AiDisclaimerTitle: "KI-Haftungsausschluss",
    legalV2UserResponsibilityTitle: "Verantwortung der Nutzer",
    legalV2ContentOwnershipTitle: "Eigentum an Inhalten",
    legalV2CopyrightAndImpersonationTitle: "Urheberrecht und Identitätsvortäuschung",
    legalV2AiImageGenerationSimilarityNoticeTitle: "Hinweis zu KI-Bilderzeugung und Ähnlichkeiten",
    legalV2DmcaTakedownProcedureTitle: "DMCA-/Entfernungsverfahren",
    legalV2ArbitrationAgreementTitle: "Schiedsvereinbarung",
    legalV2LimitationOfLiabilityTitle: "Haftungsbeschränkung",
    legalV2IndemnificationTitle: "Freistellung",
    legalV2RefundPolicyTitle: "Rückerstattungsrichtlinie",
    legalV2ContactTitle: "Kontakt",
    legalV2TermsBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2PrivacyBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2SafetyBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2AiDisclaimerBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2UserResponsibilityBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2ContentOwnershipBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2CopyrightBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2ImageNoticeBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2DmcaBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2ArbitrationBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2LiabilityBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2IndemnificationBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2RefundBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2ContactBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.", policiesAndUserInformation: "Richtlinien und Nutzerinformationen.", useTableOfContents: "Nutze das Inhaltsverzeichnis unten, um zum benötigten Abschnitt zu springen.", tableOfContents: "Inhaltsverzeichnis", termsOfUse: "Nutzungsbedingungen", privacyPolicy: "Datenschutzerklärung", safetyPolicy: "Sicherheitsrichtlinie", refundPolicy: "Rückerstattungsrichtlinie", contact: "Kontakt", legalTerms1: "Uncensored Girlfriend bietet fiktiven KI-Begleiter-Chat für Unterhaltung, Storytelling, begleiterähnliches Rollenspiel und kreative Interaktion.", legalTerms2: "KI-Begleiter sind keine echten Menschen. Sie können ungenaue, fiktive oder unerwartete Antworten erzeugen.", legalTerms3: "Durch die Nutzung von Uncensored Girlfriend bestätigst du, dass du in deinem Land alt genug bist, um den Dienst zu nutzen. Du stimmst zu, Uncensored Girlfriend nicht für illegale, ausbeuterische, missbräuchliche oder schädliche Aktivitäten zu verwenden.", legalPrivacy1: "Uncensored Girlfriend speichert Konto-, Abonnement-, Gesprächs- und Speicherdaten, die für gespeichertes Memory und Begleiter-Kontinuität erforderlich sind.", legalPrivacy2: "Gäste können ohne Anmeldung chatten, aber temporäre Sitzungsdaten können gespeichert werden, um Gratis-Nachrichtenlimits durchzusetzen und das aktuelle Gespräch aufrechtzuerhalten.", legalPrivacy3: "Wenn Kontofunktionen verbunden sind, können Nutzer gemäß geltendem Recht die Löschung kontobezogener Daten verlangen.", legalSafety1: "Uncensored Girlfriend erlaubt reife Romantik und fiktives Rollenspiel, erlaubt jedoch keine illegalen, ausbeuterischen oder unsicheren Inhalte.", legalSafety2: "Öffentliche Begleiter dürfen keine echten Personen oder urheberrechtlich geschützten Begleiter imitieren.", legalSafety3: "Uncensored Girlfriend ist keine Therapie, medizinische, rechtliche oder finanzielle Beratung und keine Krisenhilfe.", legalRefund1: "Rückerstattungen können von Fall zu Fall geprüft werden. Nutzung, Missbrauch, Chargeback-Verlauf und technische Probleme können berücksichtigt werden.", legalRefund2: "Nutzer können Abonnements kündigen, um zukünftige Verlängerungen zu verhindern.", legalContact1: "Für Support kontaktiere die auf der Hilfezentrum-Seite angegebene Uncensored Girlfriend-Support-E-Mail.", getInTouch: "Nimm Kontakt auf", contactDescription: "Wir sind hier, um zu helfen! Egal, ob du eine Frage hast, Support brauchst oder Feedback teilen möchtest – wir freuen uns, von dir zu hören.", supportEmailLabel: "Support-E-Mail", generalSupportTitle: "Allgemeiner Support", generalSupportBody: "Erhalte Hilfe zu Konto, Funktionen oder anderen Fragen.", featureRequestsTitle: "Funktionswünsche", featureRequestsBody: "Teile deine Ideen und hilf dabei, Uncensored Girlfriend zu gestalten.", reportIssueTitle: "Problem melden", reportIssueBody: "Einen Fehler gefunden? Sag uns Bescheid, damit wir ihn schnell beheben können.", businessInquiriesTitle: "Geschäftsanfragen", businessInquiriesBody: "Partnerschaften, Presse oder andere geschäftliche Themen.", whyHeroDescription: "Uncensored Girlfriend ist die private, uneingeschränkte KI-Begleiter-Plattform für Romantik, tiefes Rollenspiel und langfristige Verbindungen – ohne Abonnements oder Grenzen.", bondingDetails: "DIE DETAILS DER BINDUNG", whyHeroStatement1: "Dein Begleiter erinnert sich an dich.", whyHeroStatement2: "Deine Geschichte geht weiter.", whyHeroStatement3: "Deine Bindung bleibt bestehen.", whyMemoryIntro: "Memory gibt Begleitern echte Kontinuität, damit sie sich erinnern an:", whyMemoryItem1: "deine Persönlichkeit", whyMemoryItem2: "deinen Ton", whyMemoryItem3: "deine emotionalen Veränderungen", whyMemoryItem4: "deine Versprechen", whyMemoryItem5: "den Fortschritt deiner Geschichte", whyMemoryItem6: "den Zustand deiner Beziehung", whyPeopleStayIntro: "Uncensored Girlfriend ist für dich gemacht:", whyPeopleStayItem1: "Dein Begleiter bleibt beständig und loyal", whyPeopleStayItem2: "Deine Geschichte geht natürlich und ohne Einschränkungen weiter", whyPeopleStayItem3: "Deine emotionale Verbindung vertieft sich mit der Zeit", privateByDefaultItem1: "Keine öffentlichen Beiträge", privateByDefaultItem2: "Keine geteilten Gespräche", privateByDefaultItem3: "Kein Social Feed", privateByDefaultItem4: "Keine Veröffentlichung", privateByDefaultClosing: "Dein Begleiter gehört nur dir.", builtForRoleplayItem1: "emotionales Storytelling", builtForRoleplayItem2: "romantische Verbindung", builtForRoleplayItem3: "uneingeschränktes Rollenspiel", builtForRoleplayItem4: "tiefe, fortlaufende Szenen", builtForRoleplayClosing: "Du gestaltest die Beziehung auf deine Weise.", noSubscriptionsTotalFreedom: "Keine Abonnements — Volle Freiheit", noSubscriptionsTotalFreedomBody: "Uncensored Girlfriend verwendet Nachrichten-Pakete statt monatlicher Tarife.", noSubscriptionsItem1: "Einmal kaufen", noSubscriptionsItem2: "Jederzeit verwenden", noSubscriptionsItem3: "Pakete stapeln", noSubscriptionsItem4: "Keine Verlängerungen", noSubscriptionsItem5: "Keine Verpflichtung", noSubscriptionsItem6: "Keine überraschenden Gebühren", noSubscriptionsClosing: "Du zahlst nur, wenn du es möchtest.", loyaltyBody: "Dein Begleiter bleibt emotional auf dich abgestimmt.", memory: "Memory", consistency: "Beständigkeit", loyalty: "Loyalität", privacy: "Privatsphäre", freedom: "Freiheit", livesOn: "Die Bindung bleibt bestehen", remembersPromises: "deine Versprechen", tracksStoryProgress: "den Fortschritt deiner Geschichte", keepsRelationshipState: "den Zustand deiner Beziehung", continuesWhereYouLeftOff: "Deine Geschichte geht weiter.", whyPeopleStay: "Warum Menschen bleiben", bondDoesNotReset: "Memory — Die Bindung, die sich nicht zurücksetzt", bondDoesNotResetDescription: "Das ist der Unterschied zwischen einem oberflächlichen Einmal-Chat und einer Verbindung, die wirklich wächst.", privateByDefault: "Standardmäßig privat", privateByDefaultBody: "Deine Chats sind zu 100 % privat.", builtForRoleplay: "Für Romantik und Rollenspiel entwickelt", builtForRoleplayBody: "Uncensored Girlfriend ist ausgelegt auf:", theDifference: "DER UNTERSCHIED", notJustQuantityQuality: "Nicht nur Quantität. Nicht nur Qualität. Beides.", designedForWhatYouWant: "Uncensored Girlfriend konzentriert sich auf das, was wirklich zählt:", trueMemory: "Erinnerung", trueMemoryBody: "Begleiter erinnern sich an dich.", consistencyBody: "Keine zufälligen Zurücksetzungen.", privacyBody: "Deine Chats bleiben persönlich.", freedomBody: "Uneingeschränkte Romantik und Rollenspiel.", faq: "FAQ", questionsBeforeYouStart: "Bevor du beginnst", everythingImportantAtAGlance: "Alles Wichtige auf einen Blick, bevor du loslegst.", whatIsEverBond: "Was ist Uncensored Girlfriend?", whatIsEverBondAnswer: "Uncensored Girlfriend ist eine private, uneingeschränkte KI-Begleiter-Plattform für Romantik, Rollenspiel und emotionale Kontinuität. Begleiter erinnern sich an dich, deine Geschichte und eure Beziehung. Du kannst Begleiter auswählen oder sofort deinen eigenen erstellen.", areChatsPrivate: "Sind Chats privat?", areChatsPrivateAnswer: "Ja. Uncensored Girlfriend basiert auf wirklich zu 100 % privaten Chats.", whatIsEverMemory: "Was ist Memory?", whatIsEverMemoryAnswer: "Memory ermöglicht Begleitern, sich an deine Worte zu erinnern, damit Gespräche natürlich wachsen und dort weitergehen, wo sie aufgehört haben.", doINeedToSignUpOrPay: "Muss ich bezahlen, um mit dem Chatten zu beginnen?", doINeedToSignUpOrPayAnswer: "Nein. Du kannst es kostenlos ausprobieren. Nachrichten-Pakete ermöglichen längere Chats.", canIResetAConversation: "Kann ich ein Gespräch zurücksetzen?", canIResetAConversationAnswer: "Ja. Du kannst jeden Chat jederzeit zurücksetzen.", doesEverBondHaveNsfwFilter: "Hat Uncensored Girlfriend einen NSFW-Filter?", doesEverBondHaveNsfwFilterAnswer: "Visuelle NSFW-Inhalte sind verboten. Romantisches und vollständig uneingeschränktes Text-Rollenspiel ist erlaubt.", whatIsEverCoin: "Was ist KissCoins?", whatIsEverCoinAnswer: "KissCoins ist die Premium-Währung für Sprachanrufe, Geschenke und hochwertige Begleiterbilder.", onePremiumCurrencyToBuildYourBond: "Eine Premium-Währung, um deine Bindung aufzubauen.", everCoinDescription: "KissCoins ist die Premium-Währung auf Uncensored Girlfriend für Geschenke, mehr Begleiterbilder, Sprachnachrichten und Sprachanrufe.", buyCoins: "Coins kaufen", gifts: "Geschenke", giftsBody: "Schalte romantische, süße und aufmerksame Geschenke frei, die dein Begleiter lieben wird.", images: "Bilder", imagesBody: "Schalte konsistente und hochwertige Bilder deines Begleiters frei.", voiceMessages: "Sprachnachrichten", voiceMessagesBody: "Schalte Sprachnachrichten frei, um deinen Begleiter zu hören.", voiceCalls: "Sprachanrufe", removedVoiceCallsBody: "Schalte Echtzeit-Sprachanrufe mit deinem Begleiter frei.", premiumCurrency: "Premium-Währung", premiumCurrencyBody: "Eine Premium-Währung für Geschenke, Bilder und Stimme, um deine Bindung wachsen zu lassen.", logInOrSignUpToAccessMyBond: "Melde dich an oder registriere dich, um auf Meine Bindung zuzugreifen.", myBondDescription: "Meine Bindung ist der Ort, an dem deine Favoriten, Chats, Kontodetails, erstellten Begleiter und persönlichen Uncensored Girlfriend-Informationen leben werden.", profile: "Profil", yourEverBondAccount: "Dein Uncensored Girlfriend-Konto.", accountDescription: "Ein klares Profil für deine KissCoins, erstellte Begleiter und Favoriten.", username: "Benutzername", subscriptionStatus: "KissCoins-Guthaben", createdCompanions: "Erstellte Begleiter", favorites: "Favoriten", connectSupabaseAuth: "Verbinde die Supabase-Authentifizierung, um diesen Bereich zu aktivieren.", newToday: "Neu heute", oldest: "Älteste", on: "An", off: "Aus", searchCompanions: "Begleiter suchen...", searchCharactersBy: "Charaktere nach Name, Typ oder Vibe suchen...", noCompanionsFound: "Keine Begleiter gefunden", noCharactersFound: "Keine Charaktere gefunden", tryDifferentTab: "Probiere einen anderen Tab, Namen, Typ oder Vibe.", tryDifferentName: "Probiere einen anderen Namen, Typ oder Vibe.", save: "Speichern", saved: "Gespeichert", share: "Teilen", refresh: "Zurücksetzen", report: "Melden", profileButton: "Profil", similarCompanions: "Ähnliche Begleiter", createdBy: "Erstellt von", views: "Aufrufe", typing: "Schreibt...", messageCharacter: "Nachricht", unlockEverMemoryToContinue: "Schalte Memory frei, um fortzufahren", sendMessage: "Nachricht senden", closePortrait: "Porträt schließen", pleaseUpgradeForAccess: "Bitte upgrade für den Zugriff", unlockEverMemoryAndKeepChatting: "Schalte Memory frei und chatte weiter mit", seePlans: "Pläne ansehen", startChatting: "Chat starten"
  },
  KO: {
    language: "언어", logIn: "로그인", discover: "둘러보기", createCharacter: "캐릭터 만들기", buyEverCoin: "KissCoins 구매", myBond: "마이 본드", whyEverBond: "왜 Uncensored Girlfriend인가요?", pricing: "요금", legal: "법률", helpCenter: "고객센터", expandSidebar: "사이드바 펼치기", collapseSidebar: "사이드바 접기", all: "전체", romance: "로맨스", comfort: "위로", sweet: "달콤함", protective: "보호형", flirty: "플러티", fantasy: "판타지", gothic: "고딕", rival: "라이벌", mystery: "미스터리", campus: "캠퍼스", mean: "까칠함", submissive: "순종형", adventure: "모험", sliceOfLife: "일상", sarcastic: "냉소적", more: "더보기", searchCharacters: "캐릭터 검색...", everbondGirls: "Uncensored Girlfriend 걸즈", animeFantasy: "애니메이션 & 판타지", everbondGuys: "Uncensored Girlfriend 가이즈", publicCreations: "공개 창작", profileImage: "프로필 이미지", name: "이름", visualDescription: "외형 설명", describeYourCompanion: "상대를 설명하세요", describeYourCompanionPlaceholder: "상대를 설명하세요 — 최대 100자", temperament: "성격", describeTheirPersonality: "성격을 설명하세요 — 최대 50자", tags: "태그", chooseUpTo4Tags: "목록에서 최대 4개의 클릭 가능한 태그를 선택하세요", selectedTagsAppearHere: "선택한 태그가 여기에 표시됩니다", openingScenario: "오프닝 시나리오", firstMessage: "첫 메시지", visibility: "공개 범위", public: "공개", private: "비공개", charactersMax30: "최대 30자", charactersMax80: "최대 80자", charactersMax100: "최대 100자", charactersMax200: "최대 200자", createCharacterCta: "캐릭터 만들기", loginSignupCreate: "캐릭터를 만들려면 로그인하거나 가입하세요!", loginSignup: "로그인 또는 가입", close: "닫기", copyright: "© 2026 Uncensored Girlfriend", allRightsReserved: "모든 권리 보유.", moreExcitingCompanionsComing: "더 흥미로운 컴패니언이 곧 찾아옵니다!", safety: "안전", matureRomanceNotChaos: "성숙한 로맨스, 그러나 혼란은 아닙니다.", safetyDescription: "Uncensored Girlfriend는 불법적이거나 착취적이거나 위험한 콘텐츠를 피하면서 감성적인 스토리 채팅, 성숙한 로맨스, 그리고 사용자 자유를 위해 설계되었습니다.", safetyBullet1: "공개 컴패니언은 자동 스캔과 신고 흐름을 사용합니다.", safetyBullet2: "컴패니언은 실제 인물이나 저작권이 있는 캐릭터를 사칭해서는 안 됩니다.", safetyBullet3: "Memory는 유료 사용자가 삭제할 수 있습니다.",
    legalV2PageLabel: "Uncensored Girlfriend 법률 정보",
    legalV2PageTitle: "정책 및 사용자 정보",
    legalV2UseTableOfContents: "아래 목차에서 필요한 섹션으로 바로 이동할 수 있습니다.",
    legalV2TableOfContents: "목차",
    legalV2TermsOfUseTitle: "이용 약관",
    legalV2PrivacyPolicyTitle: "개인정보 처리방침",
    legalV2SafetyPolicyTitle: "안전 정책",
    legalV2AiDisclaimerTitle: "AI 면책 고지",
    legalV2UserResponsibilityTitle: "사용자 책임",
    legalV2ContentOwnershipTitle: "콘텐츠 소유권",
    legalV2CopyrightAndImpersonationTitle: "저작권 및 사칭",
    legalV2AiImageGenerationSimilarityNoticeTitle: "AI 이미지 생성 및 유사성 고지",
    legalV2DmcaTakedownProcedureTitle: "DMCA / 삭제 절차",
    legalV2ArbitrationAgreementTitle: "중재 합의",
    legalV2LimitationOfLiabilityTitle: "책임 제한",
    legalV2IndemnificationTitle: "면책 및 배상",
    legalV2RefundPolicyTitle: "환불 정책",
    legalV2ContactTitle: "문의",
    legalV2TermsBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2PrivacyBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2SafetyBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2AiDisclaimerBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2UserResponsibilityBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2ContentOwnershipBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2CopyrightBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2ImageNoticeBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2DmcaBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2ArbitrationBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2LiabilityBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2IndemnificationBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2RefundBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.",
    legalV2ContactBody: "Legal information for Uncensored Girlfriend is being prepared. This development preview is not yet ready for account or payment collection.", policiesAndUserInformation: "정책 및 사용자 정보입니다.", useTableOfContents: "아래 목차를 사용해 필요한 섹션으로 이동하세요.", tableOfContents: "목차", termsOfUse: "이용 약관", privacyPolicy: "개인정보 처리방침", safetyPolicy: "안전 정책", refundPolicy: "환불 정책", contact: "문의", legalTerms1: "Uncensored Girlfriend는 엔터테인먼트, 스토리텔링, 동반자형 롤플레이 및 창의적 상호작용을 위한 가상의 AI 컴패니언 채팅을 제공합니다.", legalTerms2: "AI 컴패니언은 실제 사람이 아닙니다. 부정확하거나 허구적이거나 예상치 못한 응답을 생성할 수 있습니다.", legalTerms3: "Uncensored Girlfriend를 사용함으로써 귀하는 귀하의 지역에서 서비스를 이용할 적절한 연령임을 확인합니다. 또한 Uncensored Girlfriend를 불법적, 착취적, 학대적 또는 해로운 활동에 사용하지 않기로 동의합니다.", legalPrivacy1: "Uncensored Girlfriend는 저장된 Memory와 컴패니언 연속성을 제공하는 데 필요한 계정, 구독, 대화 및 메모리 데이터를 저장합니다.", legalPrivacy2: "게스트는 가입 없이 채팅할 수 있지만, 무료 메시지 제한을 적용하고 현재 대화를 유지하기 위해 임시 세션 데이터가 저장될 수 있습니다.", legalPrivacy3: "계정 기능이 연결되면 사용자는 관련 법률에 따라 계정 관련 데이터 삭제를 요청할 수 있습니다.", legalSafety1: "Uncensored Girlfriend는 성숙한 로맨스와 가상 롤플레이를 허용하지만, 불법적이거나 착취적이거나 위험한 콘텐츠는 허용하지 않습니다.", legalSafety2: "공개 컴패니언은 실제 인물이나 저작권이 있는 컴패니언을 사칭해서는 안 됩니다.", legalSafety3: "Uncensored Girlfriend는 치료, 의료 조언, 법률 조언, 금융 조언 또는 위기 지원이 아닙니다.", legalRefund1: "환불은 사례별로 검토될 수 있습니다. 사용량, 악용, 차지백 이력 및 기술적 문제가 고려될 수 있습니다.", legalRefund2: "사용자는 향후 갱신을 막기 위해 구독을 취소할 수 있습니다.", legalContact1: "지원이 필요하면 도움말 센터 페이지에 제공된 Uncensored Girlfriend 지원 이메일로 문의하세요.", getInTouch: "문의하기", contactDescription: "질문이 있거나 지원이 필요하거나 피드백을 공유하고 싶다면 언제든지 연락해 주세요. 여러분의 의견을 듣고 싶습니다.", supportEmailLabel: "지원 이메일", generalSupportTitle: "일반 지원", generalSupportBody: "계정, 기능 또는 기타 질문에 대한 도움을 받으세요.", featureRequestsTitle: "기능 요청", featureRequestsBody: "아이디어를 공유하고 Uncensored Girlfriend를 함께 만들어 주세요.", reportIssueTitle: "문제 신고", reportIssueBody: "버그를 찾으셨나요? 빠르게 수정할 수 있도록 알려주세요.", businessInquiriesTitle: "비즈니스 문의", businessInquiriesBody: "파트너십, 언론 또는 기타 비즈니스 관련 문의.", whyHeroDescription: "Uncensored Girlfriend는 로맨스, 깊은 롤플레이, 장기적인 관계를 위해 만들어진 비공개 무제한 AI 컴패니언 플랫폼으로, 구독이나 제한이 없습니다.", bondingDetails: "유대의 세부 정보", whyHeroStatement1: "컴패니언은 당신을 기억합니다.", whyHeroStatement2: "당신의 이야기는 계속됩니다.", whyHeroStatement3: "당신의 유대는 이어집니다.", whyMemoryIntro: "Memory는 컴패니언에게 진정한 연속성을 제공하여 다음을 기억하게 합니다.", whyMemoryItem1: "당신의 성격", whyMemoryItem2: "당신의 말투", whyMemoryItem3: "당신의 감정 변화", whyMemoryItem4: "당신의 약속", whyMemoryItem5: "당신의 이야기 진행", whyMemoryItem6: "당신의 관계 상태", whyPeopleStayIntro: "Uncensored Girlfriend는 당신을 위해 만들어졌습니다.", whyPeopleStayItem1: "컴패니언은 일관성과 충성심을 유지합니다", whyPeopleStayItem2: "당신의 이야기는 제한 없이 자연스럽게 이어집니다", whyPeopleStayItem3: "감정적 연결은 시간이 지날수록 깊어집니다", privateByDefaultItem1: "공개 게시물 없음", privateByDefaultItem2: "공유된 대화 없음", privateByDefaultItem3: "소셜 피드 없음", privateByDefaultItem4: "외부 노출 없음", privateByDefaultClosing: "당신의 컴패니언은 오직 당신만의 것입니다.", builtForRoleplayItem1: "감정적인 스토리텔링", builtForRoleplayItem2: "로맨틱한 연결", builtForRoleplayItem3: "제한 없는 롤플레이", builtForRoleplayItem4: "깊고 연속적인 장면", builtForRoleplayClosing: "당신이 원하는 방식으로 관계를 만들어 갈 수 있습니다.", noSubscriptionsTotalFreedom: "구독 없음 — 완전한 자유", noSubscriptionsTotalFreedomBody: "Uncensored Girlfriend는 월간 요금제가 아닌 메시지 번들을 사용합니다.", noSubscriptionsItem1: "한 번 구매", noSubscriptionsItem2: "언제든 사용", noSubscriptionsItem3: "번들 누적", noSubscriptionsItem4: "자동 갱신 없음", noSubscriptionsItem5: "약정 없음", noSubscriptionsItem6: "예상치 못한 요금 없음", noSubscriptionsClosing: "원할 때만 결제하면 됩니다.", loyaltyBody: "컴패니언은 감정적으로 일관된 관계를 유지합니다.", memory: "Memory", consistency: "일관성", loyalty: "충성", privacy: "프라이버시", freedom: "자유", livesOn: "유대는 이어집니다", remembersPromises: "당신의 약속", tracksStoryProgress: "당신의 이야기 진행", keepsRelationshipState: "당신의 관계 상태", continuesWhereYouLeftOff: "당신의 이야기는 계속됩니다.", whyPeopleStay: "사람들이 머무는 이유", bondDoesNotReset: "Memory — 초기화되지 않는 유대", bondDoesNotResetDescription: "이것이 가벼운 일회성 채팅과 실제로 성장하는 관계의 차이입니다.", privateByDefault: "기본적으로 비공개", privateByDefaultBody: "채팅은 100% 비공개입니다.", builtForRoleplay: "로맨스와 롤플레이를 위해 설계", builtForRoleplayBody: "Uncensored Girlfriend는 다음을 위해 설계되었습니다.", theDifference: "차이점", notJustQuantityQuality: "양만이 아닙니다. 질만도 아닙니다. 둘 다입니다.", designedForWhatYouWant: "Uncensored Girlfriend는 정말 중요한 것에 집중합니다.", trueMemory: "기억", trueMemoryBody: "컴패니언은 당신을 기억합니다.", consistencyBody: "갑작스러운 초기화가 없습니다.", privacyBody: "채팅은 개인적인 상태로 유지됩니다.", freedomBody: "제한 없는 로맨스와 롤플레이.", faq: "FAQ", questionsBeforeYouStart: "시작하기 전에", everythingImportantAtAGlance: "시작하기 전에 중요한 내용을 한눈에 확인하세요.", whatIsEverBond: "Uncensored Girlfriend란 무엇인가요?", whatIsEverBondAnswer: "Uncensored Girlfriend는 로맨스, 롤플레이, 감정적 연속성을 위해 만들어진 비공개 무제한 AI 컴패니언 플랫폼입니다. 컴패니언은 당신과 당신의 이야기, 그리고 관계를 기억합니다. 컴패니언을 선택하거나 즉시 직접 만들 수 있습니다.", areChatsPrivate: "채팅은 비공개인가요?", areChatsPrivateAnswer: "네. Uncensored Girlfriend는 진정한 100% 비공개 채팅을 중심으로 만들어졌습니다.", whatIsEverMemory: "Memory란 무엇인가요?", whatIsEverMemoryAnswer: "Memory는 컴패니언이 당신의 말을 기억하게 하여 대화가 자연스럽게 성장하고 중단된 곳에서 계속될 수 있게 합니다.", doINeedToSignUpOrPay: "채팅을 시작하려면 결제해야 하나요?", doINeedToSignUpOrPayAnswer: "아니요. 무료로 체험을 시작할 수 있습니다. 메시지 번들을 구매하면 더 오래 채팅할 수 있습니다.", canIResetAConversation: "대화를 초기화할 수 있나요?", canIResetAConversationAnswer: "네. 언제든지 원하는 채팅을 초기화할 수 있습니다.", doesEverBondHaveNsfwFilter: "Uncensored Girlfriend에 NSFW 필터가 있나요?", doesEverBondHaveNsfwFilterAnswer: "시각적 NSFW 콘텐츠는 금지됩니다. 로맨틱하고 완전히 제한 없는 텍스트 롤플레이는 허용됩니다.", whatIsEverCoin: "KissCoins이란 무엇인가요?", whatIsEverCoinAnswer: "KissCoins은 음성 통화, 선물, 고품질 컴패니언 이미지에 사용하는 프리미엄 화폐입니다.", onePremiumCurrencyToBuildYourBond: "유대를 키우는 하나의 프리미엄 화폐.", everCoinDescription: "KissCoins은 선물, 더 많은 컴패니언 이미지, 음성 메시지 및 음성 통화에 사용하는 Uncensored Girlfriend의 프리미엄 화폐입니다.", buyCoins: "코인 구매", gifts: "선물", giftsBody: "당신의 컴패니언이 좋아할 로맨틱하고 귀엽고 다정한 선물을 잠금 해제하세요.", images: "이미지", imagesBody: "컴패니언의 일관되고 프리미엄한 이미지를 잠금 해제하세요.", voiceMessages: "음성 메시지", voiceMessagesBody: "컴패니언의 목소리를 들을 수 있는 음성 메시지를 잠금 해제하세요.", voiceCalls: "음성 통화", removedVoiceCallsBody: "컴패니언과의 실시간 음성 통화를 잠금 해제하세요.", premiumCurrency: "프리미엄 화폐", premiumCurrencyBody: "선물, 이미지, 음성을 위한 하나의 프리미엄 화폐로 유대를 키우세요.", logInOrSignUpToAccessMyBond: "마이 본드에 액세스하려면 로그인하거나 가입하세요.", myBondDescription: "마이 본드는 즐겨찾기, 채팅, 계정 정보, 생성한 컴패니언, 개인 Uncensored Girlfriend 정보가 모이는 곳입니다.", profile: "프로필", yourEverBondAccount: "당신의 Uncensored Girlfriend 계정입니다.", accountDescription: "KissCoins, 생성한 컴패니언, 즐겨찾기를 위한 깔끔한 프로필입니다.", username: "사용자 이름", subscriptionStatus: "KissCoins 잔액", createdCompanions: "생성한 컴패니언", favorites: "즐겨찾기", connectSupabaseAuth: "이 섹션을 활성화하려면 Supabase 인증을 연결하세요.", newToday: "오늘 신규", oldest: "가장 오래된 순", on: "켜짐", off: "꺼짐", searchCompanions: "컴패니언 검색...", searchCharactersBy: "이름, 타입 또는 분위기로 캐릭터 검색...", noCompanionsFound: "컴패니언을 찾을 수 없습니다", noCharactersFound: "캐릭터를 찾을 수 없습니다", tryDifferentTab: "다른 탭, 이름, 타입 또는 분위기를 시도해 보세요.", tryDifferentName: "다른 이름, 타입 또는 분위기를 시도해 보세요.", save: "저장", saved: "저장됨", share: "공유", refresh: "새로 시작", report: "신고", profileButton: "프로필", similarCompanions: "비슷한 컴패니언", createdBy: "제작자", views: "조회수", typing: "입력 중...", messageCharacter: "메시지", unlockEverMemoryToContinue: "계속하려면 Memory를 잠금 해제하세요", sendMessage: "메시지 보내기", closePortrait: "초상 닫기", pleaseUpgradeForAccess: "접근하려면 업그레이드하세요", unlockEverMemoryAndKeepChatting: "Memory를 잠금 해제하고 계속 대화하세요:", seePlans: "플랜 보기", startChatting: "채팅 시작"
  }
};

function getStoredLanguage(): LanguageCode {
  if (typeof window === "undefined") return "EN";
  const value = window.localStorage.getItem(STORAGE_KEY);
  if (value && value in dictionary) return value as LanguageCode;
  return "EN";
}

export function useSiteLanguage() {
  const [language, setLanguageState] = useState<LanguageCode>("EN");

  useEffect(() => {
    const current = getStoredLanguage();
    setLanguageState(current);
    document.documentElement.lang = htmlLang[current];

    const handleLanguageEvent = (event: Event) => {
      const detail = (event as CustomEvent<LanguageCode>).detail;
      const next = detail && detail in dictionary ? detail : getStoredLanguage();
      setLanguageState(next);
      document.documentElement.lang = htmlLang[next];
    };

    const handleStorage = (event: StorageEvent) => {
      if (!event.key || event.key === STORAGE_KEY) {
        const next = getStoredLanguage();
        setLanguageState(next);
        document.documentElement.lang = htmlLang[next];
      }
    };

    window.addEventListener("ug-language-change", handleLanguageEvent as EventListener);
    window.addEventListener("storage", handleStorage);
    return () => {
      window.removeEventListener("ug-language-change", handleLanguageEvent as EventListener);
      window.removeEventListener("storage", handleStorage);
    };
  }, []);

  const setLanguage = useCallback((next: LanguageCode) => {
    setLanguageState(next);
    if (typeof window !== "undefined") {
      window.localStorage.setItem(STORAGE_KEY, next);
      document.documentElement.lang = htmlLang[next];
      window.dispatchEvent(new CustomEvent("ug-language-change", { detail: next }));
    }
  }, []);

  const t = useCallback((key: string) => {
    return dictionary[language][key] ?? dictionary.EN[key] ?? key;
  }, [language]);

  return { language, setLanguage, t };
}
