-- DEPRECATED: do not apply this file.
--
-- The canonical database definition for Uncensored Girlfriend is the ordered
-- migration history in ./migrations/. This repository previously contained an
-- obsolete pre-migration EverBond-era schema here with incompatible table and
-- column types. It has intentionally been replaced to prevent accidental use.
--
-- To create a clean database, use the Supabase migration workflow against a
-- new project. Never import another business's users, payments, chats,
-- credentials, secrets, or production storage objects.
