-- EverBond Partner Traffic Engine
-- Universal partner economics: 100% days 1-30, 80% days 31-180, 50% lifetime.
-- Partner clock begins on first eligible earning. 5% platform protection is applied
-- before commission and is configurable per terms version.

begin;

create table if not exists public.partner_terms_versions (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  version integer not null,
  first_30_rate_bps integer not null default 10000 check (first_30_rate_bps between 0 and 10000),
  through_180_rate_bps integer not null default 8000 check (through_180_rate_bps between 0 and 10000),
  lifetime_rate_bps integer not null default 5000 check (lifetime_rate_bps between 0 and 10000),
  platform_protection_bps integer not null default 500 check (platform_protection_bps between 0 and 5000),
  payout_minimum_minor integer not null default 500 check (payout_minimum_minor >= 1),
  effective_from timestamptz not null default now(),
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  unique (name, version)
);

create unique index if not exists partner_terms_one_default_idx
  on public.partner_terms_versions ((is_default)) where is_default;

insert into public.partner_terms_versions (
  name, version, first_30_rate_bps, through_180_rate_bps, lifetime_rate_bps,
  platform_protection_bps, payout_minimum_minor, effective_from, is_default
)
select 'EverBond Universal Partner Program', 1, 10000, 8000, 5000, 500, 500, now(), true
where not exists (select 1 from public.partner_terms_versions where is_default = true);

create table if not exists public.partners (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique check (slug = lower(slug) and slug ~ '^[a-z0-9][a-z0-9-]{1,58}[a-z0-9]$'),
  public_name text not null,
  partner_type text not null default 'creator',
  source_platform text,
  contact_handle text,
  contact_email text,
  status text not null default 'invited' check (status in ('invited','active','suspended','terminated')),
  terms_version_id uuid not null references public.partner_terms_versions(id),
  activated_at timestamptz,
  agreement_accepted_at timestamptz,
  age_confirmed_at timestamptz,
  first_eligible_earning_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists partners_status_idx on public.partners(status);
create unique index if not exists partners_contact_email_uidx on public.partners(lower(contact_email)) where contact_email is not null;

create table if not exists public.partner_invites (
  id uuid primary key default gen_random_uuid(),
  partner_id uuid not null references public.partners(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  claimed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists partner_invites_partner_idx on public.partner_invites(partner_id, created_at desc);

create table if not exists public.partner_sessions (
  id uuid primary key default gen_random_uuid(),
  partner_id uuid not null references public.partners(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  revoked_at timestamptz,
  last_seen_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists partner_sessions_partner_idx on public.partner_sessions(partner_id, expires_at desc);

create table if not exists public.partner_links (
  id uuid primary key default gen_random_uuid(),
  partner_id uuid not null references public.partners(id) on delete cascade,
  code text not null unique,
  campaign_key text,
  destination_path text not null default '/',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  check (code = lower(code) and code ~ '^[a-z0-9][a-z0-9-]{1,80}$')
);

create index if not exists partner_links_partner_idx on public.partner_links(partner_id, created_at);

create table if not exists public.partner_clicks (
  id bigint generated by default as identity primary key,
  partner_id uuid not null references public.partners(id) on delete cascade,
  link_id uuid references public.partner_links(id) on delete set null,
  campaign_key text,
  source_platform text,
  occurred_at timestamptz not null default now()
);

create index if not exists partner_clicks_partner_time_idx on public.partner_clicks(partner_id, occurred_at desc);

create table if not exists public.partner_attributions (
  user_id uuid primary key,
  partner_id uuid not null references public.partners(id),
  link_id uuid references public.partner_links(id) on delete set null,
  clicked_at timestamptz not null,
  locked_at timestamptz not null default now(),
  source text not null default 'referral_cookie'
);

create index if not exists partner_attributions_partner_idx on public.partner_attributions(partner_id, locked_at desc);

create table if not exists public.partner_economic_source_state (
  id uuid primary key default gen_random_uuid(),
  partner_id uuid not null references public.partners(id) on delete restrict,
  referred_user_id uuid not null,
  source_key text not null,
  source_type text not null check (source_type in ('eligible_cash_release','service_cost')),
  source_id uuid,
  current_amount_usd numeric(20,8) not null default 0,
  raw_cash_release_usd numeric(20,8) not null default 0,
  platform_protection_usd numeric(20,8) not null default 0,
  effective_at timestamptz not null,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique (partner_id, source_key)
);

create index if not exists partner_econ_state_partner_time_idx
  on public.partner_economic_source_state(partner_id, effective_at, source_type);
create index if not exists partner_econ_state_user_idx
  on public.partner_economic_source_state(referred_user_id);

create table if not exists public.partner_economic_events (
  id uuid primary key default gen_random_uuid(),
  partner_id uuid not null references public.partners(id) on delete restrict,
  referred_user_id uuid not null,
  source_key text not null,
  source_type text not null check (source_type in ('eligible_cash_release','service_cost')),
  delta_amount_usd numeric(20,8) not null,
  prior_amount_usd numeric(20,8) not null,
  new_amount_usd numeric(20,8) not null,
  effective_at timestamptz not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists partner_econ_events_partner_idx
  on public.partner_economic_events(partner_id, created_at desc);

create table if not exists public.partner_finance_state (
  partner_id uuid primary key references public.partners(id) on delete restrict,
  current_commission_usd numeric(20,8) not null default 0,
  negative_carry_usd numeric(20,8) not null default 0,
  first_eligible_earning_at timestamptz,
  last_reconciled_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.partner_commission_events (
  id uuid primary key default gen_random_uuid(),
  partner_id uuid not null references public.partners(id) on delete restrict,
  terms_version_id uuid not null references public.partner_terms_versions(id),
  rate_bps integer not null check (rate_bps between 0 and 10000),
  eligible_profit_delta_usd numeric(20,8) not null,
  amount_usd numeric(20,8) not null,
  event_type text not null check (event_type in ('earning','adjustment')),
  event_key text not null unique,
  effective_at timestamptz not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists partner_commission_events_partner_idx
  on public.partner_commission_events(partner_id, created_at desc);

create table if not exists public.partner_payout_accounts (
  partner_id uuid primary key references public.partners(id) on delete cascade,
  provider text not null default 'dropp',
  provider_creator_id text,
  onboarding_status text not null default 'not_started'
    check (onboarding_status in ('not_started','pending','ready','restricted','disabled')),
  payout_enabled boolean not null default false,
  provider_metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists partner_payout_account_provider_uidx
  on public.partner_payout_accounts(provider, provider_creator_id)
  where provider_creator_id is not null;

create table if not exists public.partner_payouts (
  id uuid primary key default gen_random_uuid(),
  partner_id uuid not null references public.partners(id) on delete restrict,
  amount_minor integer not null check (amount_minor > 0),
  currency_code text not null default 'USD' check (currency_code = 'USD'),
  status text not null default 'reserved'
    check (status in ('reserved','processing','paid','failed','cancelled')),
  provider text not null default 'dropp',
  provider_payout_id text,
  payout_reference text not null unique,
  failure_code text,
  failure_message text,
  requested_at timestamptz not null default now(),
  processing_at timestamptz,
  paid_at timestamptz,
  failed_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists partner_payouts_partner_idx on public.partner_payouts(partner_id, requested_at desc);
create index if not exists partner_payouts_status_idx on public.partner_payouts(status, requested_at);
create unique index if not exists partner_payout_provider_reference_uidx
  on public.partner_payouts(provider, provider_payout_id)
  where provider_payout_id is not null;

create table if not exists public.partner_prospects (
  id uuid primary key default gen_random_uuid(),
  partner_id uuid references public.partners(id) on delete set null,
  platform text,
  handle text,
  public_name text,
  contact_email text,
  public_contact_url text,
  niche text,
  status text not null default 'discovered'
    check (status in ('discovered','qualified','prepared','contacted','responded','activated','declined','suppressed')),
  fit_score integer check (fit_score between 0 and 100),
  metadata jsonb not null default '{}'::jsonb,
  discovered_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists partner_prospects_status_idx on public.partner_prospects(status, fit_score desc nulls last);

create table if not exists public.partner_outreach_events (
  id uuid primary key default gen_random_uuid(),
  prospect_id uuid references public.partner_prospects(id) on delete set null,
  partner_id uuid references public.partners(id) on delete set null,
  channel text not null,
  event_type text not null,
  destination text,
  message_subject text,
  message_body text,
  provider_message_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists partner_outreach_partner_idx on public.partner_outreach_events(partner_id, created_at desc);

create table if not exists public.partner_outreach_suppressions (
  contact_email text primary key,
  reason text not null default 'unsubscribe',
  created_at timestamptz not null default now()
);

create table if not exists public.partner_outreach_unsubscribe_tokens (
  id uuid primary key default gen_random_uuid(),
  contact_email text not null,
  token_hash text not null unique,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists partner_unsubscribe_email_idx on public.partner_outreach_unsubscribe_tokens(lower(contact_email), created_at desc);

-- Server-only storage. Browser clients never receive direct access to partner financial tables.
alter table public.partner_terms_versions enable row level security;
alter table public.partners enable row level security;
alter table public.partner_invites enable row level security;
alter table public.partner_sessions enable row level security;
alter table public.partner_links enable row level security;
alter table public.partner_clicks enable row level security;
alter table public.partner_attributions enable row level security;
alter table public.partner_economic_source_state enable row level security;
alter table public.partner_economic_events enable row level security;
alter table public.partner_finance_state enable row level security;
alter table public.partner_commission_events enable row level security;
alter table public.partner_payout_accounts enable row level security;
alter table public.partner_payouts enable row level security;
alter table public.partner_prospects enable row level security;
alter table public.partner_outreach_events enable row level security;
alter table public.partner_outreach_suppressions enable row level security;
alter table public.partner_outreach_unsubscribe_tokens enable row level security;

create or replace function public.partner_default_terms_id()
returns uuid
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select id from public.partner_terms_versions where is_default = true order by effective_from desc limit 1;
$$;

create or replace function public.partner_sync_source(
  p_partner_id uuid,
  p_user_id uuid,
  p_source_key text,
  p_source_type text,
  p_source_id uuid,
  p_amount_usd numeric,
  p_raw_cash_release_usd numeric,
  p_platform_protection_usd numeric,
  p_effective_at timestamptz,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_old numeric(20,8) := 0;
  v_exists boolean := false;
  v_new numeric(20,8) := round(coalesce(p_amount_usd,0),8);
begin
  select current_amount_usd, true into v_old, v_exists
  from public.partner_economic_source_state
  where partner_id = p_partner_id and source_key = p_source_key
  for update;

  if not found then
    v_old := 0;
    v_exists := false;
  end if;

  if not v_exists then
    insert into public.partner_economic_source_state (
      partner_id, referred_user_id, source_key, source_type, source_id,
      current_amount_usd, raw_cash_release_usd, platform_protection_usd,
      effective_at, metadata, updated_at
    ) values (
      p_partner_id, p_user_id, p_source_key, p_source_type, p_source_id,
      v_new, round(coalesce(p_raw_cash_release_usd,0),8),
      round(coalesce(p_platform_protection_usd,0),8),
      p_effective_at, coalesce(p_metadata,'{}'::jsonb), now()
    );
  else
    update public.partner_economic_source_state
    set current_amount_usd = v_new,
        raw_cash_release_usd = round(coalesce(p_raw_cash_release_usd,0),8),
        platform_protection_usd = round(coalesce(p_platform_protection_usd,0),8),
        effective_at = p_effective_at,
        metadata = coalesce(p_metadata,'{}'::jsonb),
        updated_at = now()
    where partner_id = p_partner_id and source_key = p_source_key;
  end if;

  if abs(v_new - coalesce(v_old,0)) > 0.00000001 then
    insert into public.partner_economic_events (
      partner_id, referred_user_id, source_key, source_type,
      delta_amount_usd, prior_amount_usd, new_amount_usd,
      effective_at, metadata
    ) values (
      p_partner_id, p_user_id, p_source_key, p_source_type,
      round(v_new-coalesce(v_old,0),8), round(coalesce(v_old,0),8), v_new,
      p_effective_at, coalesce(p_metadata,'{}'::jsonb)
    );
  end if;
end;
$$;

create or replace function public.partner_recompute_commission(p_partner_id uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_terms public.partner_terms_versions%rowtype;
  v_first timestamptz;
  v_existing_first timestamptz;
  v_carry numeric(20,8) := 0;
  v_shareable numeric(20,8) := 0;
  v_amount numeric(20,8) := 0;
  v_reduce numeric(20,8) := 0;
  v_here numeric(20,8) := 0;
  v_elapsed_days numeric := 0;
  v_profit_100 numeric(20,8) := 0;
  v_profit_80 numeric(20,8) := 0;
  v_profit_50 numeric(20,8) := 0;
  v_target_100 numeric(20,8) := 0;
  v_target_80 numeric(20,8) := 0;
  v_target_50 numeric(20,8) := 0;
  v_current numeric(20,8) := 0;
  v_delta numeric(20,8) := 0;
  v_terms_id uuid;
  v_now timestamptz := now();
  r record;
begin
  perform pg_advisory_xact_lock(hashtextextended('partner:' || p_partner_id::text, 0));

  select t.* into v_terms
  from public.partners p
  join public.partner_terms_versions t on t.id = p.terms_version_id
  where p.id = p_partner_id;
  if not found then return; end if;
  v_terms_id := v_terms.id;

  insert into public.partner_finance_state(partner_id)
  values (p_partner_id)
  on conflict (partner_id) do nothing;

  select first_eligible_earning_at into v_existing_first
  from public.partner_finance_state
  where partner_id = p_partner_id
  for update;
  v_first := v_existing_first;

  -- Rebuild the partner's current eligible-profit position from authoritative
  -- economic source state. Negative economics always consume the most recent
  -- positive profit first, so a later provider cost/refund reverses prior earnings
  -- instead of merely waiting to offset some future customer purchase.
  for r in
    select source_key, source_type, current_amount_usd, effective_at
    from public.partner_economic_source_state
    where partner_id = p_partner_id
      and abs(current_amount_usd) > 0.00000001
    order by effective_at,
      case when source_type='service_cost' then 0 else 1 end,
      source_key
  loop
    v_amount := round(r.current_amount_usd,8);

    if v_amount < 0 then
      v_reduce := abs(v_amount);

      -- LIFO reduction across the contractual earning buckets. Because the loop
      -- is chronological, the latest bucket is always the correct first target.
      if v_profit_50 > 0 and v_reduce > 0 then
        v_here := least(v_profit_50,v_reduce);
        v_profit_50 := v_profit_50-v_here;
        v_reduce := v_reduce-v_here;
      end if;
      if v_profit_80 > 0 and v_reduce > 0 then
        v_here := least(v_profit_80,v_reduce);
        v_profit_80 := v_profit_80-v_here;
        v_reduce := v_reduce-v_here;
      end if;
      if v_profit_100 > 0 and v_reduce > 0 then
        v_here := least(v_profit_100,v_reduce);
        v_profit_100 := v_profit_100-v_here;
        v_reduce := v_reduce-v_here;
      end if;
      if v_reduce > 0 then
        v_carry := v_carry+v_reduce;
      end if;
      continue;
    end if;

    if v_amount <= 0 then continue; end if;

    if v_carry > 0 then
      if v_amount <= v_carry then
        v_carry := v_carry-v_amount;
        continue;
      end if;
      v_shareable := v_amount-v_carry;
      v_carry := 0;
    else
      v_shareable := v_amount;
    end if;

    if v_shareable <= 0 then continue; end if;

    if v_first is null then
      v_first := r.effective_at;
    end if;

    v_elapsed_days := greatest(extract(epoch from (r.effective_at-v_first))/86400.0,0);
    if v_elapsed_days < 30 then
      v_profit_100 := v_profit_100+v_shareable;
    elsif v_elapsed_days < 180 then
      v_profit_80 := v_profit_80+v_shareable;
    else
      v_profit_50 := v_profit_50+v_shareable;
    end if;
  end loop;

  v_profit_100 := round(v_profit_100,8);
  v_profit_80 := round(v_profit_80,8);
  v_profit_50 := round(v_profit_50,8);
  v_target_100 := round(v_profit_100*v_terms.first_30_rate_bps/10000.0,8);
  v_target_80 := round(v_profit_80*v_terms.through_180_rate_bps/10000.0,8);
  v_target_50 := round(v_profit_50*v_terms.lifetime_rate_bps/10000.0,8);

  -- The first-earning clock is permanent once it starts. Refunds and later costs
  -- may reduce entitlement, but they never restart a partner's launch-rate clock.
  if v_existing_first is null and v_first is not null then
    update public.partner_finance_state
      set first_eligible_earning_at = v_first, updated_at = v_now
      where partner_id = p_partner_id;
    update public.partners
      set first_eligible_earning_at = v_first, updated_at = v_now
      where id = p_partner_id and first_eligible_earning_at is null;
  else
    v_first := coalesce(v_existing_first,v_first);
  end if;

  -- Reconcile each schedule bucket independently. The schedule key and immutable
  -- terms-version id prevent equal rate percentages from colliding with each other.
  select coalesce(sum(amount_usd),0) into v_current
  from public.partner_commission_events
  where partner_id=p_partner_id
    and terms_version_id=v_terms_id
    and metadata->>'schedule'='days_1_30';
  v_delta := round(v_target_100-v_current,8);
  if abs(v_delta)>0.00000001 then
    insert into public.partner_commission_events(
      partner_id,terms_version_id,rate_bps,eligible_profit_delta_usd,amount_usd,
      event_type,event_key,effective_at,metadata
    ) values (
      p_partner_id,v_terms_id,v_terms.first_30_rate_bps,
      case when v_terms.first_30_rate_bps=0 then 0 else round(v_delta*10000.0/v_terms.first_30_rate_bps,8) end,
      v_delta,case when v_delta>0 then 'earning' else 'adjustment' end,
      'commission-reconcile:'||p_partner_id||':days_1_30:'||gen_random_uuid(),
      v_now,jsonb_build_object('targetUsd',v_target_100,'eligibleProfitUsd',v_profit_100,'schedule','days_1_30')
    );
  end if;

  select coalesce(sum(amount_usd),0) into v_current
  from public.partner_commission_events
  where partner_id=p_partner_id
    and terms_version_id=v_terms_id
    and metadata->>'schedule'='days_31_180';
  v_delta := round(v_target_80-v_current,8);
  if abs(v_delta)>0.00000001 then
    insert into public.partner_commission_events(
      partner_id,terms_version_id,rate_bps,eligible_profit_delta_usd,amount_usd,
      event_type,event_key,effective_at,metadata
    ) values (
      p_partner_id,v_terms_id,v_terms.through_180_rate_bps,
      case when v_terms.through_180_rate_bps=0 then 0 else round(v_delta*10000.0/v_terms.through_180_rate_bps,8) end,
      v_delta,case when v_delta>0 then 'earning' else 'adjustment' end,
      'commission-reconcile:'||p_partner_id||':days_31_180:'||gen_random_uuid(),
      v_now,jsonb_build_object('targetUsd',v_target_80,'eligibleProfitUsd',v_profit_80,'schedule','days_31_180')
    );
  end if;

  select coalesce(sum(amount_usd),0) into v_current
  from public.partner_commission_events
  where partner_id=p_partner_id
    and terms_version_id=v_terms_id
    and metadata->>'schedule'='day_181_plus';
  v_delta := round(v_target_50-v_current,8);
  if abs(v_delta)>0.00000001 then
    insert into public.partner_commission_events(
      partner_id,terms_version_id,rate_bps,eligible_profit_delta_usd,amount_usd,
      event_type,event_key,effective_at,metadata
    ) values (
      p_partner_id,v_terms_id,v_terms.lifetime_rate_bps,
      case when v_terms.lifetime_rate_bps=0 then 0 else round(v_delta*10000.0/v_terms.lifetime_rate_bps,8) end,
      v_delta,case when v_delta>0 then 'earning' else 'adjustment' end,
      'commission-reconcile:'||p_partner_id||':day_181_plus:'||gen_random_uuid(),
      v_now,jsonb_build_object('targetUsd',v_target_50,'eligibleProfitUsd',v_profit_50,'schedule','day_181_plus')
    );
  end if;

  update public.partner_finance_state
  set current_commission_usd = round(v_target_100+v_target_80+v_target_50,8),
      negative_carry_usd = round(v_carry,8),
      first_eligible_earning_at = coalesce(first_eligible_earning_at,v_first),
      last_reconciled_at = v_now,
      updated_at = v_now
  where partner_id = p_partner_id;
end;
$$;

create or replace function public.partner_sync_user(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_partner_id uuid;
  v_terms public.partner_terms_versions%rowtype;
  r record;
  v_raw numeric(20,8);
  v_protection numeric(20,8);
  v_eligible numeric(20,8);
begin
  select a.partner_id into v_partner_id
  from public.partner_attributions a
  where a.user_id = p_user_id;
  if v_partner_id is null then return; end if;

  select t.* into v_terms
  from public.partners p
  join public.partner_terms_versions t on t.id=p.terms_version_id
  where p.id=v_partner_id;
  if not found then return; end if;

  -- All service-delivery costs for an attributed user count, including free/trial/included usage.
  for r in
    select e.id, coalesce(t.created_at,e.created_at) as effective_at,
      greatest(coalesce(e.cost_usd,0)-coalesce(e.reversed_usd,0),0)::numeric as net_cost,
      e.feature, e.event_key
    from public.platform_provider_cost_events e
    left join public.evercoin_transactions t on t.id=e.evercoin_transaction_id
    where e.user_id=p_user_id
  loop
    perform public.partner_sync_source(
      v_partner_id,p_user_id,'provider-cost:'||r.id::text,'service_cost',r.id,
      -r.net_cost,0,0,r.effective_at,
      jsonb_build_object('feature',r.feature,'providerEventKey',r.event_key)
    );
  end loop;

  -- Cash-backed consumed EC only releases actual reconciled Dropp net cash.
  for r in
    select a.id, a.created_at, a.ec_amount, a.ec_reversed,
      l.status, l.net_minor, l.coins_granted, l.id as cash_lot_id
    from public.evercoin_cash_allocations a
    join public.evercoin_cash_lots l on l.id=a.cash_lot_id
    where a.user_id=p_user_id
  loop
    if r.status='active' and r.net_minor is not null and r.coins_granted>0 then
      v_raw := greatest((r.ec_amount-r.ec_reversed),0)::numeric * r.net_minor::numeric / r.coins_granted::numeric / 100.0;
    else
      v_raw := 0;
    end if;
    v_protection := v_raw * v_terms.platform_protection_bps / 10000.0;
    v_eligible := v_raw-v_protection;

    perform public.partner_sync_source(
      v_partner_id,p_user_id,'cash-release:'||r.id::text,'eligible_cash_release',r.id,
      v_eligible,v_raw,v_protection,r.created_at,
      jsonb_build_object('cashLotId',r.cash_lot_id,'protectionBps',v_terms.platform_protection_bps)
    );
  end loop;

end;
$$;

create or replace function public.partner_reconcile_all()
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare r record;
begin
  -- Sync source facts once per attributed customer, then recompute each partner
  -- once. This avoids repeatedly rebuilding the same partner commission history
  -- as the referred-customer base grows.
  for r in select user_id from public.partner_attributions order by locked_at loop
    perform public.partner_sync_user(r.user_id);
  end loop;
  for r in select id from public.partners where status in ('invited','active','suspended') order by created_at loop
    perform public.partner_recompute_commission(r.id);
  end loop;
end;
$$;

create or replace function public.partner_claim_attribution(
  p_user_id uuid,
  p_partner_id uuid,
  p_link_id uuid,
  p_clicked_at timestamptz,
  p_source text default 'referral_cookie'
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare v_inserted boolean := false; v_rows integer := 0;
begin
  if p_clicked_at < now()-interval '30 days' or p_clicked_at > now()+interval '5 minutes' then
    return false;
  end if;
  if not exists(select 1 from public.partners where id=p_partner_id and status in ('invited','active')) then
    return false;
  end if;
  if p_link_id is not null and not exists(
    select 1 from public.partner_links where id=p_link_id and partner_id=p_partner_id and is_active
  ) then return false; end if;

  insert into public.partner_attributions(user_id,partner_id,link_id,clicked_at,source)
  values(p_user_id,p_partner_id,p_link_id,p_clicked_at,coalesce(nullif(p_source,''),'referral_cookie'))
  on conflict (user_id) do nothing;
  get diagnostics v_rows = row_count;
  v_inserted := v_rows > 0;
  if v_inserted then
    insert into public.partner_finance_state(partner_id) values(p_partner_id)
    on conflict(partner_id) do nothing;
    perform public.partner_sync_user(p_user_id);
    perform public.partner_recompute_commission(p_partner_id);
  end if;
  return v_inserted;
end;
$$;

-- Partner accounting is intentionally kept off customer-critical chat/payment writes.
-- Dashboards, payout requests and the owner Safe-to-Withdraw calculation reconcile
-- synchronously instead, so a partner subsystem fault cannot break normal EverBond usage.
create or replace function public.partner_reconcile_partner(p_partner_id uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare r record;
begin
  for r in
    select user_id
    from public.partner_attributions
    where partner_id = p_partner_id
    order by locked_at
  loop
    perform public.partner_sync_user(r.user_id);
  end loop;
  perform public.partner_recompute_commission(p_partner_id);
end;
$$;

-- Returns each partner's bank-backed amount that can safely be paid right now.
create or replace function public.partner_safe_to_pay_snapshot()
returns table(partner_id uuid, unpaid_usd numeric, available_usd numeric)
language sql
security definer
set search_path=public,pg_temp
as $$
with base as (
  select public.platform_finance_summary() as j, public.platform_finance_health() as h
), vals as (
  select
    coalesce(((j->'current'->>'unusedEcReserveUsd')::numeric),0) unused_reserve,
    coalesce(((j->'current'->>'providerCostsUsd')::numeric),0) provider_costs,
    coalesce(((j->'current'->>'ownerWithdrawalsUsd')::numeric),0) owner_withdrawals,
    coalesce((h->>'healthy')::boolean,false) healthy
  from base
), proc as (
  select coalesce(sum(amount_minor)::numeric/100.0,0) payouts_received
  from public.platform_processor_payouts where provider='dropp' and currency_code='USD'
), locked as (
  select partner_id, coalesce(sum(amount_minor)::numeric/100.0,0) locked_usd
  from public.partner_payouts where status in ('reserved','processing','paid')
  group by partner_id
), locked_total as (
  select coalesce(sum(locked_usd),0) v from locked
), capacity as (
  select case when vals.healthy then greatest(proc.payouts_received-vals.unused_reserve-vals.provider_costs-vals.owner_withdrawals-prot.v-locked_total.v,0) else 0 end bank_available
  from vals cross join proc cross join locked_total cross join (select coalesce(sum(platform_protection_usd),0) v from public.partner_economic_source_state where source_type='eligible_cash_release') prot
), obligations as (
  select p.id partner_id,
    greatest(coalesce(fs.current_commission_usd,0)-coalesce(l.locked_usd,0),0) unpaid_usd,
    coalesce(fs.first_eligible_earning_at,p.first_eligible_earning_at,p.created_at) sort_at
  from public.partners p
  join public.partner_finance_state fs on fs.partner_id=p.id
  left join locked l on l.partner_id=p.id
  where p.status in ('invited','active')
), ranked as (
  select o.*,
    coalesce(sum(o.unpaid_usd) over(order by o.sort_at,o.partner_id rows between unbounded preceding and 1 preceding),0) prior_unpaid
  from obligations o
)
select r.partner_id, round(r.unpaid_usd,8),
  round(greatest(least(r.unpaid_usd,c.bank_available-r.prior_unpaid),0),8) available_usd
from ranked r cross join capacity c;
$$;

create or replace function public.partner_request_payout(p_partner_id uuid, p_amount_minor integer)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_partner public.partners%rowtype;
  v_terms public.partner_terms_versions%rowtype;
  v_available numeric:=0;
  v_account public.partner_payout_accounts%rowtype;
  v_id uuid;
  v_ref text;
begin
  perform pg_advisory_xact_lock(hashtextextended('partner-payout-pool',0));
  -- Payout capacity is global. Reconcile every partner first so an earlier
  -- partner with stale entitlement cannot be skipped by the FIFO bank-cash gate.
  perform public.partner_reconcile_all();

  select * into v_partner from public.partners where id=p_partner_id for update;
  if not found then return jsonb_build_object('ok',false,'error','PARTNER_NOT_FOUND'); end if;
  if v_partner.status<>'active' or v_partner.agreement_accepted_at is null or v_partner.age_confirmed_at is null then
    return jsonb_build_object('ok',false,'error','PARTNERSHIP_NOT_ACTIVE');
  end if;
  select * into v_terms from public.partner_terms_versions where id=v_partner.terms_version_id;
  if p_amount_minor < v_terms.payout_minimum_minor then
    return jsonb_build_object('ok',false,'error','PAYOUT_BELOW_MINIMUM','minimumMinor',v_terms.payout_minimum_minor);
  end if;
  select * into v_account from public.partner_payout_accounts where partner_id=p_partner_id;
  if not found or v_account.payout_enabled is not true or v_account.onboarding_status<>'ready' then
    return jsonb_build_object('ok',false,'error','PAYOUT_ONBOARDING_REQUIRED');
  end if;

  select available_usd into v_available from public.partner_safe_to_pay_snapshot() where partner_id=p_partner_id;
  v_available := coalesce(v_available,0);
  if p_amount_minor > floor(v_available*100.0) then
    return jsonb_build_object('ok',false,'error','PAYOUT_EXCEEDS_AVAILABLE','availableMinor',floor(v_available*100.0));
  end if;

  v_ref := 'partner-'||p_partner_id::text||'-'||gen_random_uuid()::text;
  insert into public.partner_payouts(partner_id,amount_minor,status,provider,payout_reference)
  values(p_partner_id,p_amount_minor,'reserved','dropp',v_ref)
  returning id into v_id;

  return jsonb_build_object('ok',true,'payoutId',v_id,'payoutReference',v_ref,'amountMinor',p_amount_minor);
end;
$$;

create or replace function public.partner_dashboard_summary(p_partner_id uuid)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_partner public.partners%rowtype;
  v_terms public.partner_terms_versions%rowtype;
  v_state public.partner_finance_state%rowtype;
  v_available numeric:=0;
  v_clicks bigint:=0; v_signups bigint:=0; v_buyers bigint:=0;
  v_ec_purchased numeric:=0; v_ec_consumed numeric:=0;
  v_raw_release numeric:=0; v_protection numeric:=0; v_costs numeric:=0;
  v_paid numeric:=0; v_locked numeric:=0; v_positive_earned numeric:=0; v_adjustments numeric:=0;
  v_current_rate integer; v_day integer:=0;
  v_account jsonb;
  v_campaigns jsonb;
begin
  -- Available cash is shared across all partners, so keep the global FIFO
  -- snapshot current before presenting a cashout amount.
  perform public.partner_reconcile_all();
  select * into v_partner from public.partners where id=p_partner_id;
  if not found then return null; end if;
  select * into v_terms from public.partner_terms_versions where id=v_partner.terms_version_id;
  select * into v_state from public.partner_finance_state where partner_id=p_partner_id;
  select available_usd into v_available from public.partner_safe_to_pay_snapshot() where partner_id=p_partner_id;

  select count(*) into v_clicks from public.partner_clicks where partner_id=p_partner_id;
  select count(*) into v_signups from public.partner_attributions where partner_id=p_partner_id;
  select count(distinct a.user_id) into v_buyers
    from public.partner_attributions a join public.evercoin_payment_orders o on o.user_id=a.user_id
    where a.partner_id=p_partner_id and o.status='paid';
  select coalesce(sum(l.coins_granted),0) into v_ec_purchased
    from public.partner_attributions a join public.evercoin_cash_lots l on l.user_id=a.user_id
    where a.partner_id=p_partner_id and l.status='active';
  select coalesce(sum(greatest(c.ec_amount-c.ec_reversed,0)),0) into v_ec_consumed
    from public.partner_attributions a join public.evercoin_cash_allocations c on c.user_id=a.user_id
    where a.partner_id=p_partner_id;
  select coalesce(sum(raw_cash_release_usd),0),coalesce(sum(platform_protection_usd),0)
    into v_raw_release,v_protection from public.partner_economic_source_state
    where partner_id=p_partner_id and source_type='eligible_cash_release';
  select coalesce(sum(abs(current_amount_usd)),0) into v_costs
    from public.partner_economic_source_state where partner_id=p_partner_id and source_type='service_cost';
  select coalesce(sum(amount_minor)::numeric/100.0,0) into v_paid
    from public.partner_payouts where partner_id=p_partner_id and status='paid';
  select coalesce(sum(amount_minor)::numeric/100.0,0) into v_locked
    from public.partner_payouts where partner_id=p_partner_id and status in ('reserved','processing','paid');
  select coalesce(sum(case when amount_usd>0 then amount_usd else 0 end),0),
         coalesce(sum(case when amount_usd<0 then amount_usd else 0 end),0)
    into v_positive_earned,v_adjustments
    from public.partner_commission_events where partner_id=p_partner_id;

  if v_state.first_eligible_earning_at is null then
    v_current_rate:=v_terms.first_30_rate_bps;
  else
    v_day:=greatest(floor(extract(epoch from (now()-v_state.first_eligible_earning_at))/86400.0)::int,0)+1;
    if v_day<=30 then v_current_rate:=v_terms.first_30_rate_bps;
    elsif v_day<=180 then v_current_rate:=v_terms.through_180_rate_bps;
    else v_current_rate:=v_terms.lifetime_rate_bps; end if;
  end if;

  select coalesce(jsonb_agg(jsonb_build_object(
      'campaign',coalesce(x.campaign_key,'default'),'clicks',x.clicks,'signups',x.signups
    ) order by x.clicks desc),'[]'::jsonb) into v_campaigns
  from (
    select c.campaign_key,count(*) clicks,
      (select count(*) from public.partner_attributions a where a.partner_id=p_partner_id and a.link_id=c.link_id) signups
    from public.partner_clicks c where c.partner_id=p_partner_id
    group by c.campaign_key,c.link_id
    limit 20
  ) x;

  select coalesce(to_jsonb(pa)-'partner_id'-'provider_metadata','{}'::jsonb) into v_account
  from public.partner_payout_accounts pa where pa.partner_id=p_partner_id;

  return jsonb_build_object(
    'partner',jsonb_build_object('id',v_partner.id,'slug',v_partner.slug,'publicName',v_partner.public_name,
      'status',v_partner.status,'partnerType',v_partner.partner_type,'sourcePlatform',v_partner.source_platform,
      'activatedAt',v_partner.activated_at,'firstEligibleEarningAt',v_state.first_eligible_earning_at),
    'terms',jsonb_build_object('first30RateBps',v_terms.first_30_rate_bps,'through180RateBps',v_terms.through_180_rate_bps,
      'lifetimeRateBps',v_terms.lifetime_rate_bps,'platformProtectionBps',v_terms.platform_protection_bps,
      'payoutMinimumMinor',v_terms.payout_minimum_minor,'currentRateBps',v_current_rate,'currentDay',v_day),
    'performance',jsonb_build_object('clicks',v_clicks,'signups',v_signups,'buyers',v_buyers,
      'evercoinPurchased',v_ec_purchased,'paidEcConsumed',v_ec_consumed),
    'economics',jsonb_build_object('cashReleasedUsd',round(v_raw_release,2),'serviceCostsUsd',round(v_costs,2),
      'platformProtectionUsd',round(v_protection,2),'eligibleProfitUsd',round(greatest(v_raw_release-v_protection-v_costs,0),2),
      'negativeCarryUsd',round(coalesce(v_state.negative_carry_usd,0),2),'currentCommissionUsd',round(coalesce(v_state.current_commission_usd,0),2)),
    'earnings',jsonb_build_object('positiveEarnedUsd',round(v_positive_earned,2),'adjustmentsUsd',round(v_adjustments,2),
      'currentEntitlementUsd',round(coalesce(v_state.current_commission_usd,0),2),'availableUsd',floor(greatest(coalesce(v_available,0),0)*100.0)/100.0,
      'lockedOrPaidUsd',round(v_locked,2),'paidUsd',round(v_paid,2),
      'pendingUsd',round(greatest(coalesce(v_state.current_commission_usd,0)-v_locked-coalesce(v_available,0),0),2)),
    'payoutAccount',coalesce(v_account,'{}'::jsonb),'campaigns',coalesce(v_campaigns,'[]'::jsonb)
  );
end;
$$;

create or replace function public.partner_traffic_engine_summary()
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_invited bigint:=0; v_active bigint:=0; v_earning bigint:=0;
  v_clicks bigint:=0; v_signups bigint:=0; v_buyers bigint:=0;
  v_gross numeric:=0; v_net numeric:=0; v_outstanding_ec numeric:=0;
  v_raw numeric:=0; v_protection numeric:=0; v_costs numeric:=0; v_eligible numeric:=0; v_commission numeric:=0;
  v_paid numeric:=0; v_processing numeric:=0; v_available numeric:=0;
  v_locked numeric:=0; v_protected_cost numeric:=0; v_overpayment numeric:=0;
  v_top jsonb; v_channels jsonb;
begin
  perform public.partner_reconcile_all();
  select count(*) filter(where status='invited'),count(*) filter(where status='active') into v_invited,v_active from public.partners;
  select count(*) into v_earning from public.partner_finance_state where current_commission_usd>0;
  select count(*) into v_clicks from public.partner_clicks;
  select count(*) into v_signups from public.partner_attributions;
  select count(distinct a.user_id) into v_buyers from public.partner_attributions a join public.evercoin_payment_orders o on o.user_id=a.user_id and o.status='paid';
  select coalesce(sum(l.gross_minor)::numeric/100.0,0),coalesce(sum(l.net_minor)::numeric/100.0,0),coalesce(sum(l.coins_remaining),0)
    into v_gross,v_net,v_outstanding_ec
    from public.evercoin_cash_lots l join public.partner_attributions a on a.user_id=l.user_id where l.status='active';
  select coalesce(sum(raw_cash_release_usd),0),coalesce(sum(platform_protection_usd),0),
    coalesce(sum(case when source_type='service_cost' then abs(current_amount_usd) else 0 end),0)
    into v_raw,v_protection,v_costs from public.partner_economic_source_state;
  select coalesce(sum(greatest(x.raw-x.protection-x.costs,0)),0) into v_eligible from (
    select p.id,
      coalesce(sum(s.raw_cash_release_usd),0) raw,
      coalesce(sum(s.platform_protection_usd),0) protection,
      coalesce(sum(case when s.source_type='service_cost' then abs(s.current_amount_usd) else 0 end),0) costs
    from public.partners p left join public.partner_economic_source_state s on s.partner_id=p.id
    group by p.id
  ) x;
    select coalesce(sum(current_commission_usd),0) into v_commission from public.partner_finance_state;
  select coalesce(sum(amount_minor)::numeric/100.0,0) into v_paid from public.partner_payouts where status='paid';
  select coalesce(sum(amount_minor)::numeric/100.0,0) into v_processing from public.partner_payouts where status in('reserved','processing');
  select coalesce(sum(available_usd),0) into v_available from public.partner_safe_to_pay_snapshot();

  with locked as (
    select partner_id,coalesce(sum(amount_minor)::numeric/100.0,0) amt from public.partner_payouts where status in('reserved','processing','paid') group by partner_id
  )
  select coalesce(sum(coalesce(l.amt,0)),0),
    coalesce(sum(greatest(coalesce(fs.current_commission_usd,0),coalesce(l.amt,0))),0),
    coalesce(sum(greatest(coalesce(l.amt,0)-coalesce(fs.current_commission_usd,0),0)),0)
  into v_locked,v_protected_cost,v_overpayment
  from public.partners p left join public.partner_finance_state fs on fs.partner_id=p.id left join locked l on l.partner_id=p.id;

  select coalesce(jsonb_agg(to_jsonb(x) order by x.commission_usd desc),'[]'::jsonb) into v_top from (
    select p.slug,p.public_name as "publicName",p.source_platform as "sourcePlatform",
      round(coalesce(fs.current_commission_usd,0),2) as commission_usd,
      count(distinct a.user_id) as signups
    from public.partners p left join public.partner_finance_state fs on fs.partner_id=p.id
    left join public.partner_attributions a on a.partner_id=p.id
    group by p.id,fs.current_commission_usd order by coalesce(fs.current_commission_usd,0) desc limit 15
  ) x;

  select coalesce(jsonb_agg(to_jsonb(x) order by x.clicks desc),'[]'::jsonb) into v_channels from (
    select coalesce(p.source_platform,'other') channel,
      coalesce(sum(pc.clicks),0) clicks,coalesce(sum(pa.signups),0) signups
    from public.partners p
    left join (select partner_id,count(*) clicks from public.partner_clicks group by partner_id) pc on pc.partner_id=p.id
    left join (select partner_id,count(*) signups from public.partner_attributions group by partner_id) pa on pa.partner_id=p.id
    group by coalesce(p.source_platform,'other')
    order by coalesce(sum(pc.clicks),0) desc limit 20
  ) x;

  return jsonb_build_object(
    'partners',jsonb_build_object('invited',v_invited,'active',v_active,'generatingEarnings',v_earning),
    'traffic',jsonb_build_object('clicks',v_clicks,'signups',v_signups,'buyers',v_buyers),
    'sales',jsonb_build_object('referredGrossUsd',round(v_gross,2),'referredDroppNetUsd',round(v_net,2),'outstandingEc',v_outstanding_ec,
      'cashReleasedUsd',round(v_raw,2),'serviceCostsUsd',round(v_costs,2),'platformProtectionUsd',round(v_protection,2),
      'eligiblePartnerProfitUsd',round(v_eligible,2)),
    'commissions',jsonb_build_object('currentEntitlementUsd',round(v_commission,2),'availableUsd',round(v_available,2),
      'processingUsd',round(v_processing,2),'paidUsd',round(v_paid,2),'lockedOrPaidUsd',round(v_locked,2),
      'protectedPartnerCostUsd',round(v_protected_cost,2),'overpaymentCarryUsd',round(v_overpayment,2),
      'everbondRetainedContributionUsd',round(greatest(v_eligible-v_protected_cost,0),2)),
    'topPartners',coalesce(v_top,'[]'::jsonb),'channels',coalesce(v_channels,'[]'::jsonb)
  );
end;
$$;

-- Partner commissions are protected immediately from owner withdrawals. If a later
-- refund creates an overpayment, actual reserved/processing/paid payouts remain protected
-- until future entitlement catches up.
create or replace function public.platform_finance_summary_safe(
  p_from timestamptz default null,
  p_to timestamptz default null
)
returns jsonb
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare
  v_base jsonb; v_current jsonb; v_period jsonb; v_health jsonb;
  v_base_economic_safe numeric:=0; v_economic_safe numeric:=0;
  v_unused_reserve numeric:=0; v_provider_costs numeric:=0; v_owner_withdrawals numeric:=0;
  v_payouts_received numeric:=0; v_period_payouts numeric:=0; v_bank_cap numeric:=0;
  v_safe numeric:=0; v_waiting numeric:=0; v_partner_cost numeric:=0; v_partner_platform_reserve numeric:=0;
  v_partner_entitlement numeric:=0; v_partner_locked numeric:=0; v_partner_unpaid numeric:=0;
begin
  -- Never let stale partner economics inflate owner Safe to Withdraw. This runs only
  -- on finance/admin paths, not customer chat/payment requests.
  perform public.partner_reconcile_all();
  v_base:=public.platform_finance_summary(p_from,p_to);
  v_current:=coalesce(v_base->'current','{}'::jsonb);
  v_period:=coalesce(v_base->'period','{}'::jsonb);
  v_health:=public.platform_finance_health();

  v_base_economic_safe:=coalesce((v_current->>'safeToWithdrawUsd')::numeric,0);
  v_unused_reserve:=coalesce((v_current->>'unusedEcReserveUsd')::numeric,0);
  v_provider_costs:=coalesce((v_current->>'providerCostsUsd')::numeric,0);
  v_owner_withdrawals:=coalesce((v_current->>'ownerWithdrawalsUsd')::numeric,0);

  with locked as (
    select partner_id,coalesce(sum(amount_minor)::numeric/100.0,0) amt
    from public.partner_payouts where status in('reserved','processing','paid') group by partner_id
  )
  select coalesce(sum(coalesce(fs.current_commission_usd,0)),0),
         coalesce(sum(coalesce(l.amt,0)),0),
         coalesce(sum(greatest(coalesce(fs.current_commission_usd,0),coalesce(l.amt,0))),0),
         coalesce(sum(greatest(coalesce(fs.current_commission_usd,0)-coalesce(l.amt,0),0)),0)
  into v_partner_entitlement,v_partner_locked,v_partner_cost,v_partner_unpaid
  from public.partners p
  left join public.partner_finance_state fs on fs.partner_id=p.id
  left join locked l on l.partner_id=p.id;

  select coalesce(sum(platform_protection_usd),0) into v_partner_platform_reserve
  from public.partner_economic_source_state where source_type='eligible_cash_release';

  v_economic_safe:=greatest(v_base_economic_safe-v_partner_cost-v_partner_platform_reserve,0);

  select coalesce(sum(p.amount_minor)::numeric/100.0,0) into v_payouts_received
  from public.platform_processor_payouts p where p.provider='dropp' and p.currency_code='USD';
  select coalesce(sum(p.amount_minor)::numeric/100.0,0) into v_period_payouts
  from public.platform_processor_payouts p
  where p.provider='dropp' and p.currency_code='USD'
    and p.received_at>=coalesce(p_from,'-infinity'::timestamptz)
    and p.received_at<coalesce(p_to,'infinity'::timestamptz);

  v_bank_cap:=greatest(v_payouts_received-v_unused_reserve-v_provider_costs-v_owner_withdrawals-v_partner_cost-v_partner_platform_reserve,0);
  v_safe:=least(v_economic_safe,v_bank_cap);
  if coalesce((v_health->>'healthy')::boolean,false) is not true then v_safe:=0; end if;
  v_waiting:=greatest(v_economic_safe-v_safe,0);

  v_current:=v_current||jsonb_build_object(
    'economicSafeToWithdrawUsd',round(v_economic_safe,2),
    'processorPayoutsReceivedUsd',round(v_payouts_received,2),
    'bankCashAfterProtectionUsd',round(v_bank_cap,2),
    'profitAwaitingPayoutUsd',round(v_waiting,2),
    'safeToWithdrawUsd',round(v_safe,2),
    'financeHealthy',coalesce((v_health->>'healthy')::boolean,false),
    'partnerCommissionEntitlementUsd',round(v_partner_entitlement,2),
    'partnerLockedOrPaidUsd',round(v_partner_locked,2),
    'partnerProtectedCostUsd',round(v_partner_cost,2),
    'partnerPlatformProtectionReserveUsd',round(v_partner_platform_reserve,2),
    'partnerUnpaidLiabilityUsd',round(v_partner_unpaid,2)
  );
  v_period:=v_period||jsonb_build_object('processorPayoutsReceivedUsd',round(v_period_payouts,2));
  return jsonb_build_object('current',v_current,'period',v_period);
end;
$$;

-- Ensure the existing atomic owner-withdrawal RPC automatically uses the new safe summary.
-- It already calls platform_finance_summary_safe(), so no withdrawal function rewrite is needed.

revoke all on public.partner_terms_versions,public.partners,public.partner_invites,public.partner_sessions,
  public.partner_links,public.partner_clicks,public.partner_attributions,public.partner_economic_source_state,
  public.partner_economic_events,public.partner_finance_state,public.partner_commission_events,
  public.partner_payout_accounts,public.partner_payouts,public.partner_prospects,public.partner_outreach_events,
  public.partner_outreach_suppressions,public.partner_outreach_unsubscribe_tokens
from anon,authenticated,public;

revoke all on sequence public.partner_clicks_id_seq from anon,authenticated,public;

grant all on public.partner_terms_versions,public.partners,public.partner_invites,public.partner_sessions,
  public.partner_links,public.partner_clicks,public.partner_attributions,public.partner_economic_source_state,
  public.partner_economic_events,public.partner_finance_state,public.partner_commission_events,
  public.partner_payout_accounts,public.partner_payouts,public.partner_prospects,public.partner_outreach_events,
  public.partner_outreach_suppressions,public.partner_outreach_unsubscribe_tokens
  to service_role;
grant usage,select on sequence public.partner_clicks_id_seq to service_role;

revoke execute on function public.partner_default_terms_id() from public,anon,authenticated;
revoke execute on function public.partner_sync_source(uuid,uuid,text,text,uuid,numeric,numeric,numeric,timestamptz,jsonb) from public,anon,authenticated;
revoke execute on function public.partner_recompute_commission(uuid) from public,anon,authenticated;
revoke execute on function public.partner_sync_user(uuid) from public,anon,authenticated;
revoke execute on function public.partner_reconcile_all() from public,anon,authenticated;
revoke execute on function public.partner_reconcile_partner(uuid) from public,anon,authenticated;
revoke execute on function public.partner_claim_attribution(uuid,uuid,uuid,timestamptz,text) from public,anon,authenticated;
revoke execute on function public.partner_safe_to_pay_snapshot() from public,anon,authenticated;
revoke execute on function public.partner_request_payout(uuid,integer) from public,anon,authenticated;
revoke execute on function public.partner_dashboard_summary(uuid) from public,anon,authenticated;
revoke execute on function public.partner_traffic_engine_summary() from public,anon,authenticated;

grant execute on function public.partner_default_terms_id() to service_role;
grant execute on function public.partner_sync_source(uuid,uuid,text,text,uuid,numeric,numeric,numeric,timestamptz,jsonb) to service_role;
grant execute on function public.partner_recompute_commission(uuid) to service_role;
grant execute on function public.partner_sync_user(uuid) to service_role;
grant execute on function public.partner_reconcile_all() to service_role;
grant execute on function public.partner_reconcile_partner(uuid) to service_role;
grant execute on function public.partner_claim_attribution(uuid,uuid,uuid,timestamptz,text) to service_role;
grant execute on function public.partner_safe_to_pay_snapshot() to service_role;
grant execute on function public.partner_request_payout(uuid,integer) to service_role;
grant execute on function public.partner_dashboard_summary(uuid) to service_role;
grant execute on function public.partner_traffic_engine_summary() to service_role;

commit;
